<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ángela Lomas Anglada">

<title>Bayesian Evidence Aggregation for Spam Detection</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Bayesian_Evidence_Aggegation_for_Spam_Detection_files/libs/clipboard/clipboard.min.js"></script>
<script src="Bayesian_Evidence_Aggegation_for_Spam_Detection_files/libs/quarto-html/quarto.js"></script>
<script src="Bayesian_Evidence_Aggegation_for_Spam_Detection_files/libs/quarto-html/popper.min.js"></script>
<script src="Bayesian_Evidence_Aggegation_for_Spam_Detection_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Bayesian_Evidence_Aggegation_for_Spam_Detection_files/libs/quarto-html/anchor.min.js"></script>
<link href="Bayesian_Evidence_Aggegation_for_Spam_Detection_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Bayesian_Evidence_Aggegation_for_Spam_Detection_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Bayesian_Evidence_Aggegation_for_Spam_Detection_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Bayesian_Evidence_Aggegation_for_Spam_Detection_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Bayesian_Evidence_Aggegation_for_Spam_Detection_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Bayesian Evidence Aggregation for Spam Detection</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ángela Lomas Anglada </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="librerías" class="level1">
<h1>LIBRERÍAS</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(c( "e1071", "quanteda", "tidymodels","textrecipes","readr","caret","glmnet","Matrix","pROC","dplyr","ggplot2","ggpubr", "here"))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(e1071)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Package version: 4.3.1
Unicode version: 15.1
ICU version: 74.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Parallel computing: 12 of 12 threads used.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>See https://quanteda.io for tutorials and examples.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.4.1 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ broom        1.0.10     ✔ recipes      1.3.1 
✔ dials        1.4.2      ✔ rsample      1.3.2 
✔ dplyr        1.1.4      ✔ tailor       0.1.0 
✔ ggplot2      4.0.1      ✔ tidyr        1.3.1 
✔ infer        1.1.0      ✔ tune         2.0.1 
✔ modeldata    1.5.1      ✔ workflows    1.3.0 
✔ parsnip      1.4.1      ✔ workflowsets 1.1.1 
✔ purrr        1.2.0      ✔ yardstick    1.3.2 </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ purrr::discard()        masks scales::discard()
✖ ggplot2::element()      masks e1071::element()
✖ dplyr::filter()         masks stats::filter()
✖ dplyr::lag()            masks stats::lag()
✖ rsample::permutations() masks e1071::permutations()
✖ recipes::step()         masks stats::step()
✖ tune::tune()            masks parsnip::tune(), e1071::tune()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(textrecipes)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'readr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:yardstick':

    spec</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:scales':

    col_factor</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'caret'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:yardstick':

    precision, recall, sensitivity, specificity</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:rsample':

    calibration</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    lift</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'Matrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loaded glmnet 4.1-10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Matrix)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Type 'citation("pROC")' for a citation.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'pROC'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    cov, smooth, var</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at C:/Users/angel/Desktop/UNIVERSIDAD/CUARTO DE CARRERA/Análisis_Bayesiano/Análisis_Bayesiano</code></pre>
</div>
</div>
</section>
<section id="dataset" class="level1">
<h1>DATASET</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>spam <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"spam.csv"</span>), <span class="at">fileEncoding =</span> <span class="st">"Latin1"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(spam)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(spam)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    v1
1  ham
2  ham
3 spam
4  ham
5  ham
6 spam
                                                                                                                                                           v2
1                                             Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...
2                                                                                                                               Ok lar... Joking wif u oni...
3 Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&amp;C's apply 08452810075over18's
4                                                                                                           U dun say so early hor... U c already then say...
5                                                                                               Nah I don't think he goes to usf, he lives around here though
6        FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv
  X X.1 X.2
1          
2          
3          
4          
5          
6          </code></pre>
</div>
</div>
</section>
<section id="limpiar-data-set" class="level1">
<h1>LIMPIAR DATA SET</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>spam <span class="ot">&lt;-</span> spam[, <span class="fu">c</span>(<span class="st">"v1"</span>, <span class="st">"v2"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">colnames</span>(spam)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">"spam"</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">colnames</span>(spam)[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">"text"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stopwords)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>spam<span class="sc">$</span>spam <span class="ot">&lt;-</span> <span class="fu">factor</span>(spam<span class="sc">$</span>spam)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>stop_words_list <span class="ot">&lt;-</span> <span class="fu">stopwords</span>(<span class="at">language =</span> <span class="st">"en"</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>toks <span class="ot">&lt;-</span> <span class="fu">tokens</span>(</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  spam<span class="sc">$</span>text,</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">what =</span> <span class="st">"word"</span>,</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">remove_numbers =</span> <span class="cn">TRUE</span>,</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">remove_punct =</span> <span class="cn">TRUE</span>,</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">remove_symbols =</span> <span class="cn">TRUE</span>,</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">remove_separators =</span> <span class="cn">TRUE</span>,</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">split_hyphens =</span> <span class="cn">TRUE</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>toks <span class="ot">&lt;-</span> <span class="fu">tokens_tolower</span>(toks)</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>matriz_dfm <span class="ot">&lt;-</span> toks <span class="sc">|&gt;</span> </span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>   <span class="fu">dfm</span> () <span class="sc">|&gt;</span> </span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>   <span class="fu">dfm_remove</span>(<span class="at">pattern =</span> stop_words_list) </span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>matriz_dfm <span class="ot">&lt;-</span> <span class="fu">convert</span>(matriz_dfm, <span class="at">to =</span> <span class="st">"data.frame"</span>)</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>matriz_dfm<span class="sc">$</span>spam <span class="ot">&lt;-</span> spam<span class="sc">$</span>spam</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>matriz_dfm <span class="ot">&lt;-</span> matriz_dfm[, <span class="fu">c</span>(<span class="st">"spam"</span>, <span class="fu">setdiff</span>(<span class="fu">names</span>(matriz_dfm), <span class="st">"spam"</span>))]</span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(matriz_dfm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Sacar distintos modelos (tres modelos, sacr los aciertos siendo aciertos y de esas filas, podemos</p>
<p>para el modelo 1 cuáles son las palabras más probables para que si que sean spam. Más usadas del global y una vez hecho eso diferneciarlos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>matriz_dfm<span class="sc">$</span>spam <span class="ot">&lt;-</span> <span class="fu">factor</span>(spam<span class="sc">$</span>spam, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"ham"</span>, <span class="st">"spam"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="procesamiento-del-texto" class="level1">
<h1>PROCESAMIENTO DEL TEXTO</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  <span class="co"># para reproducibilidad</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>train_index <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(matriz_dfm<span class="sc">$</span>spam, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> matriz_dfm[train_index, ]</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>test_data  <span class="ot">&lt;-</span> matriz_dfm[<span class="sc">-</span>train_index, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="modelos" class="level1">
<h1>MODELOS</h1>
<section id="modelo-svm-binario-spam-no-spam" class="level2">
<h2 class="anchored" data-anchor-id="modelo-svm-binario-spam-no-spam">MODELO SVM BINARIO (Spam / No Spam)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="st">"doc_id"</span> <span class="sc">%in%</span> <span class="fu">colnames</span>(train_data)) {</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  train_data <span class="ot">&lt;-</span> <span class="fu">subset</span>(train_data, <span class="at">select =</span> <span class="sc">-</span>doc_id)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  test_data  <span class="ot">&lt;-</span> <span class="fu">subset</span>(test_data,  <span class="at">select =</span> <span class="sc">-</span>doc_id)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Entrenar el modelo SVM </span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>svm_model <span class="ot">&lt;-</span> <span class="fu">svm</span>(</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  spam <span class="sc">~</span> ., </span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train_data,</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">kernel =</span> <span class="st">"linear"</span>,     <span class="co"># kernel "linear" para texto (rápido y efectivo)</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">cost =</span> <span class="dv">1</span>,              <span class="co"># parámetro de penalización</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">probability =</span> <span class="cn">TRUE</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in svm.default(x, y, scale = scale, ..., na.action = na.action):
Variable(s) 'melle' and 'minnaminunginte' and 'nurungu' and 'vettam' and
'breather' and 'granted' and 'fulfil' and 'sarcastic' and 'apologetic' and
'fallen' and 'actin' and 'spoilt' and 'badly' and 'sptv' and 'jersey' and
'devils' and 'wings' and 'hockey' and 'incorrect' and 'seekers' and 'barbie'
and '`ken's`' and 'operate' and 'factory' and 'ams' and '`4the`' and 'ip' and
'minecraft' and 'server' and '`0871277810910p`' and 'box42wr29c' and 'apples'
and 'pairs' and 'malarky' and 'involve' and 'imposed' and 'tmorrow.pls' and
'accomodate' and 'aaooooright' and 'excited' and 'refund' and 'os' and 'ubandu'
and 'installing' and 'disk' and 'gandhipuram' and 'pleassssssseeeeee' and
'sportsx' and 'sometme' and 'evo' and 'flash' and 'celebrations' and 'diesel'
and 'evaporated' and 'stealing' and '`employer's`' and 'prestige' and 'iphone'
and 'calling.forgot' and 'onam' and 'sirji.i' and 'person.meet' and 'insha' and
'allah.rakhesh' and 'tata' and 'aig' and 'dawns' and 'refreshed' and 'z' and
'taught' and 'becaus' and 'verifying' and 'prabu' and 'repairs' and 'followin'
and 'disastrous' and 'optimistic' and 'amy' and 'upgrdcentre' and 'oral' and
'okmail' and 'enters' and 'differ' and 'differ.be' and '`when're`' and 'mcr'
and 'jaykwon' and 'thuglyfe' and 'falconerf' and 'significance' and '`g's`' and
'scrounge' and 'ammo' and 'ak' and 'boltblue' and 'poly3' and 'slide' and
'jamz' and 'toxic' and 'topped' and '`http://www.bubbletext.com`' and 'renewal'
and 'tgxxrz' and '`x'mas`' and 'faggot' and 'pan' and 'silly' and 'uv' and
'causes' and 'mutations' and 'sunscreen' and 'thesedays' and 'mei' and 'haven'
and 'bao' and 'sugardad' and 'ridden' and 'arguing' and 'textand' and 'jjc' and
'tendencies' and 'stands' and 'nitz' and 'xclusive' and '`@clubsaisai`' and
'soiree' and 'speciale' and 'zouk' and 'paris.free' and 'roses' and
'bridgwater' and 'banter' and 'uncomfortable' and 'sonetimes' and 'rough' and
'repent' and '`carlos'll`' and 'wetherspoons' and 'cherthala.in' and 'bfore'
and 'start.i' and 'accordingly.or' and 'coming.tmorow' and 'engaged' and
'entrepreneurs' and '`alex's`' and 'corporation' and 'jelly' and 'dao' and
'neglect' and 'tattoos' and '`phone's`' and 'vibrate' and 'acting' and
'`08704439680ts`' and 'dramatic' and 'apparently' and 'uncountable' and
'smokin' and 's.nervous' and 'outbid' and 'simonwatson5120' and 'shinco' and
'plyr' and 'smsrewards' and 'notifications' and 'youi' and 'enjoyin' and
'yourjob' and 'iåõllspeak' and 'soonlots' and 'mystery' and '`1.50pm`' and
'bunkers' and 'yoyyooo' and 'permissions' and 'mac' and 'kvb' and '`1million`'
and 'ppt150x3' and 'box403' and 'w1t1jy' and 'theyre' and 'chk' and 'ms' and
'dict' and 'retired' and 'wrongly' and 'sd' and 'iåõd' and 'doesnåõt' and
'belligerent' and 'days.so' and 'finalise' and 'visit.need' and
'www.flirtparty.us' and 'replys150' and 'c52' and 'attraction.i' and 'me.she'
and 'thoughts.i' and 'her.she' and 'dream.love' and 'name.my' and 'her.my' and
'her.i' and 'her.will' and 'sorrows.i' and 'her.love' and 'proove' and
'planet.i' and 'singing' and 'praises' and 'makiing' and 'sambar.life' and
'then.will' and '`fr'ndship`' and 'needle' and '`4few`' and 'conected' and
'elvis' and 'presleys' and 'sittin' and 'drops' and 'smoked' and 'math' and
'ground.amla' and 'errors' and 'difficulties' and 'tau' and 'piah' and 'hangin'
and 'thin' and 'arguments' and 'fed' and 'himso' and 'thanx.xx' and 'snatch'
and 'relieved' and 'westonzoyland' and 'el' and 'nino' and 'didntgive' and
'bellearlier' and '`2moro`' and 'jane' and 'weirdo' and 'stalk' and 'profiles'
and 'disappeared' and 'coveragd' and 'vasai' and 'icic' and 'ax' and 'korean'
and '`leona's`' and 'nick' and 'types' and 'auntie' and 'huai' and 'arm' and
'beta' and 'before.went' and 'revision' and 'boyf' and 'interviw' and 'exeter'
and 'dartboard' and 'doubles' and 'trebles' and 'textpod' and 'www.textpod.net'
and 'ducking' and 'chinchillas' and 'headstart' and '`2.30ish`' and 'rummer'
and 'spys' and 'earliest' and 'nordstrom' and '`www.orange.co.uk/ow`' and
'bleak' and 'filled' and 'image' and 'patty' and 'haul' and 'rt' and 'pro' and
'`info@ringtoneking.co.uk`' and 'redeemable' and 'www.ringtoneking.co.uk' and
'batch' and 'fring' and '`0a`' and 'allow' and 'companies' and 'responsible'
and 'suppliers' and 'wright' and 'fly' and 'messy' and 'kilos' and 'accidant'
and 'tookplace' and 'ghodbandar' and 'slovely' and 'slip' and 'ah.now' and
'nus' and 'sc' and 'specialise' and 'wad' and 'stereo' and 'mi' and 'fires.are'
and 'entertaining' and 'hugh' and 'laurie' and 'stick' and 'praps' and 'jon'
and 'spain' and 'dinero' and 'åôrents' and '`12,000pes`' and 'panren' and
'paru' and 'dhanush' and 'needing' and 'dileep.thank' and 'muchand' and
'venugopal' and 'mentioned.tomorrow' and 'there.goodnight' and '`#150`' and
'cro1327' and 'transfr' and 'iraq' and 'afghanistan' and 'stable' and 'honest'
and 'traveling' and 'fellow' and 'lifting' and '`2price`' and '`100txt`' and
'`b'tooth`' and 'd3wv' and 'matric' and 'reception' and 'tag' and 'underwear'
and 'bras' and 'strewn' and 'pillows' and 'weaknesses' and '`knee's`' and
'exposes' and 'pulls' and 'wicked' and '`station's`' and 'heads' and 'lifebook'
and 'vpod' and 'carry' and 'mary' and 'payback' and 'practising' and 'curtsey'
and 'forwarding' and 'intention' and 'visitors' and 'rules' and
'responsibility' and 'bend' and 'thia' and 'inlude' and 'previews' and 'jot'
and 'pack' and 'store.like' and 'cereals' and 'gari' and 'bold2' and 'shadow'
and 'box420' and 'rejected' and 'nearby' and 'cliffs' and 'aluable' and
'ffectionate' and 'oveable' and 'ternal' and 'oble' and 'ruthful' and 'ntimate'
and 'atural' and 'namous' and 'progress' and 'waliking' and 'jod' and 'keris'
and 'smidgin' and 'belive' and 'accordin' and 'yummmm' and 'spoiled' and
'significant' and 'anand' and 'zogtorius' and 'iåõve' and 'posible' and
'century' and 'frwd' and 'clarification' and 'cakes' and 'cl' and 'wasted' and
'chiong' and 'torrents' and 'particularly' and 'slowing' and 'payed' and
'suganya' and 'onum' and 'car.so' and 's.i' and 'rr' and 'complementary' and
'wa14' and '`2px`' and 'drama' and 'pls.i' and 'struggling' and 'place.no' and
'ego' and 'necessity' and 'go.wait' and 'reppurcussions' and 'hcl' and
'requires' and 'freshers' and 'process.excellent' and 'needed.salary' and
'ms.suman' and 'telephonic' and 'bids' and 'reliant' and 'fwiw' and 'afford'
and 'pleasant' and 'statements' and 'risks' and 'programs' and 'snap' and
'quizclub' and '`80122300p`' and 'rwm' and 'ultimately' and 'tor' and 'motive'
and 'tui' and 'achieve' and 'korli' and 'picsfree1' and 'keyword' and 'tarot'
and 'rimac' and 'restocked' and '`2marrow`' and 'breakfast' and 'hamper' and
'reality' and '`0870737910216yrs`' and 'prasad' and '`taylor's`' and 'busy.i'
and 'ericson' and 'der' and 'luks' and 'modl' and 'palm' and 'printing' and
'handing' and 'derp' and 'abusers' and 'arr' and 'oscar' and 'affidavit' and
'twiggs' and 'courtroom' and 'showers' and 'possessiveness' and 'poured' and
'golden' and 'wtc' and 'weiyi' and 'cough' and 'pooja' and 'pimples' and
'sweatter' and 'explicitly' and 'nora' and 'butting' and 'vs' and 'cedar' and
'stopbcm' and 'sf' and 'doinat' and '`ron's`' and 'resubmit' and 'expiry' and
'studyn' and 'everyboy' and 'xxxxxxxx' and 'lined' and 'fifth' and 'woozles'
and 'weasels' and 'fucks' and 'cozy' and 'night.nobody' and 'slower' and
'maniac' and 'grinder' and 'wesley' and '`how've`' and 'initiate' and 'tallent'
and 'wasting' and 'gopalettan' and 'participate' and 'abroad' and 'xxsp' and
'visionsms.com' and 'stopcost' and 'agent' and 'goodies' and 'mat' and 'expert'
and 's.s' and 'thinl' and 'sachin.just' and 'home.love' and 'walkabout' and
'returning' and 'barred' and 'twat' and 'dungerees' and 'decking' and 'punch'
and 'opened' and 'appeal' and 'thriller' and 'director' and 'bread' and
'`thangam.it's`' and 'recycling' and 'earning' and 'lasagna' and 'drove' and
'justify' and 'hunt' and 'everyones' and 'babysitting' and 'gonnamissu' and
'buttheres' and 'aboutas' and 'merememberin' and 'asthere' and 'ofsi' and
'breakin' and 'yaxx' and 'ee' and 'poortiyagi' and 'odalebeku' and 'hanumanji'
and 'hanuman' and 'b</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Predicciones</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>svm_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(svm_model, <span class="at">newdata =</span> test_data, <span class="at">probability =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Evaluación del modelo</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>conf_matrix_svm <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(svm_pred, test_data<span class="sc">$</span>spam, <span class="at">positive =</span> <span class="st">"spam"</span>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix_svm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction ham spam
      ham  962   15
      spam   3  134
                                          
               Accuracy : 0.9838          
                 95% CI : (0.9746, 0.9904)
    No Information Rate : 0.8662          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.9278          
                                          
 Mcnemar's Test P-Value : 0.009522        
                                          
            Sensitivity : 0.8993          
            Specificity : 0.9969          
         Pos Pred Value : 0.9781          
         Neg Pred Value : 0.9846          
             Prevalence : 0.1338          
         Detection Rate : 0.1203          
   Detection Prevalence : 0.1230          
      Balanced Accuracy : 0.9481          
                                          
       'Positive' Class : spam            
                                          </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Añadir predicciones a la matriz </span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Si quieres tener una columna con las predicciones del SVM:</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>matriz_dfm<span class="sc">$</span>modelo_SVM <span class="ot">&lt;-</span> <span class="fu">predict</span>(svm_model, <span class="at">newdata =</span> matriz_dfm)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Distribución de predicciones</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(matriz_dfm<span class="sc">$</span>modelo_SVM)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 ham spam 
4841  731 </code></pre>
</div>
</div>
</section>
<section id="logístico-binario-lasso---glmnet-matriz-confusión-global" class="level2">
<h2 class="anchored" data-anchor-id="logístico-binario-lasso---glmnet-matriz-confusión-global">LOGÍSTICO BINARIO (LASSO - GLMNET) + MATRIZ CONFUSIÓN + GLOBAL</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Preparación (TRAIN)</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="st">"spam"</span> <span class="sc">%in%</span> <span class="fu">names</span>(train_data))</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="co"># y (1=spam, 0=ham)</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>train_data<span class="sc">$</span>spam_num <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(train_data<span class="sc">$</span>spam <span class="sc">==</span> <span class="st">"spam"</span>, 1L, 0L)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>y_train <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(train_data<span class="sc">$</span>spam_num)</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="co"># columnas de features (excluye objetivo y derivadas)</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>feat_cols <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="fu">colnames</span>(train_data), <span class="fu">c</span>(<span class="st">"spam"</span>, <span class="st">"spam_num"</span>))</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">length</span>(feat_cols) <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a><span class="co"># X train y limpieza de NA</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>x_train <span class="ot">&lt;-</span> <span class="fu">as</span>(<span class="fu">as.matrix</span>(<span class="fu">sapply</span>(train_data[, feat_cols, <span class="at">drop =</span> <span class="cn">FALSE</span>], as.numeric)), <span class="st">"dgCMatrix"</span>)</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>x_train[<span class="fu">is.na</span>(x_train)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">nrow</span>(x_train) <span class="sc">==</span> <span class="fu">length</span>(y_train))</span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a><span class="co">#CV (LASSO)</span></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>cvfit <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> x_train,</span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> y_train,</span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">family =</span> <span class="st">"binomial"</span>,</span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">alpha =</span> <span class="dv">1</span>,             <span class="co"># LASSO</span></span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">type.measure =</span> <span class="st">"auc"</span></span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-27"><a href="#cb44-27" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"lambda.min:"</span>, cvfit<span class="sc">$</span>lambda.min, <span class="st">" | lambda.1se:"</span>, cvfit<span class="sc">$</span>lambda<span class="fl">.1</span>se, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lambda.min: 0.001787382  | lambda.1se: 0.009992915 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#MATRIZ DE CONFUSIÓN EN </span><span class="al">TEST</span><span class="co"> (0.5 y YOUDEN)</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="st">"spam"</span> <span class="sc">%in%</span> <span class="fu">names</span>(test_data))</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>y_test <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(test_data<span class="sc">$</span>spam <span class="sc">==</span> <span class="st">"spam"</span>, 1L, 0L)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Alinear </span><span class="al">TEST</span><span class="co"> a feat_cols (añadir faltantes, quitar extras, ordenar)</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>faltan_en_test <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(feat_cols, <span class="fu">colnames</span>(test_data))</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(faltan_en_test) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (cn <span class="cf">in</span> faltan_en_test) test_data[[cn]] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>Xte_df <span class="ot">&lt;-</span> test_data[, feat_cols, drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>x_test <span class="ot">&lt;-</span> <span class="fu">as</span>(<span class="fu">as.matrix</span>(<span class="fu">sapply</span>(Xte_df, as.numeric)), <span class="st">"dgCMatrix"</span>)</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>x_test[<span class="fu">is.na</span>(x_test)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidades y etiquetas con umbral 0.5</span></span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>pred_probs_test <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">predict</span>(cvfit, <span class="at">newx =</span> x_test, <span class="at">s =</span> cvfit<span class="sc">$</span>lambda.min, <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>pred_labels_test <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(pred_probs_test <span class="sc">&gt;</span> <span class="fl">0.5</span>, 1L, 0L)</span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a>cm_05 <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(</span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(pred_labels_test, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),</span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(y_test,          <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),</span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">positive =</span> <span class="st">"1"</span></span>
<span id="cb46-23"><a href="#cb46-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb46-24"><a href="#cb46-24" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> Matriz de confusión (umbral 0.5):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Matriz de confusión (umbral 0.5):</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cm_05)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 961  19
         1   4 130
                                          
               Accuracy : 0.9794          
                 95% CI : (0.9692, 0.9869)
    No Information Rate : 0.8662          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.9069          
                                          
 Mcnemar's Test P-Value : 0.003509        
                                          
            Sensitivity : 0.8725          
            Specificity : 0.9959          
         Pos Pred Value : 0.9701          
         Neg Pred Value : 0.9806          
             Prevalence : 0.1338          
         Detection Rate : 0.1167          
   Detection Prevalence : 0.1203          
      Balanced Accuracy : 0.9342          
                                          
       'Positive' Class : 1               
                                          </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># AUC en test</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>roc_test <span class="ot">&lt;-</span> pROC<span class="sc">::</span><span class="fu">roc</span>(y_test, pred_probs_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"AUC Test (lambda.min):"</span>, <span class="fu">round</span>(pROC<span class="sc">::</span><span class="fu">auc</span>(roc_test), <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>AUC Test (lambda.min): 0.9686 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Umbral óptimo de Youden (robusto)</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>thr_youden_vec <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">coords</span>(roc_test, <span class="st">"best"</span>, <span class="at">best.method =</span> <span class="st">"youden"</span>,</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">ret =</span> <span class="st">"threshold"</span>, <span class="at">transpose =</span> <span class="cn">FALSE</span>))</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>thr_youden <span class="ot">&lt;-</span> thr_youden_vec[<span class="dv">1</span>]  <span class="co"># si hay varios, toma el primero</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Umbral Youden sugerido:"</span>, <span class="fu">round</span>(thr_youden, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Umbral Youden sugerido: 0.099 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>pred_labels_test_youden <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(pred_probs_test <span class="sc">&gt;=</span> thr_youden, 1L, 0L)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>cm_youden <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(pred_labels_test_youden, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">factor</span>(y_test,                  <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">positive =</span> <span class="st">"1"</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> Matriz de confusión (umbral Youden):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Matriz de confusión (umbral Youden):</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cm_youden)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction   0   1
         0 944  12
         1  21 137
                                          
               Accuracy : 0.9704          
                 95% CI : (0.9586, 0.9795)
    No Information Rate : 0.8662          
    P-Value [Acc &gt; NIR] : &lt;2e-16          
                                          
                  Kappa : 0.8753          
                                          
 Mcnemar's Test P-Value : 0.1637          
                                          
            Sensitivity : 0.9195          
            Specificity : 0.9782          
         Pos Pred Value : 0.8671          
         Neg Pred Value : 0.9874          
             Prevalence : 0.1338          
         Detection Rate : 0.1230          
   Detection Prevalence : 0.1418          
      Balanced Accuracy : 0.9489          
                                          
       'Positive' Class : 1               
                                          </code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#PREDICCIONES GLOBALES (train + test) y anexo a matriz_dfm</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Verifica que matriz_dfm tenga las columnas de entrenamiento</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(feat_cols <span class="sc">%in%</span> <span class="fu">colnames</span>(matriz_dfm)))</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Construir X_all a partir de feat_cols y alinear</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>matriz_pred <span class="ot">&lt;-</span> matriz_dfm[, feat_cols, drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>x_all <span class="ot">&lt;-</span> <span class="fu">as</span>(<span class="fu">as.matrix</span>(<span class="fu">sapply</span>(matriz_pred, as.numeric)), <span class="st">"dgCMatrix"</span>)</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>x_all[<span class="fu">is.na</span>(x_all)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Alineación por seguridad (mismo orden que feat_cols)</span></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>x_all_aligned <span class="ot">&lt;-</span> <span class="fu">Matrix</span>(<span class="dv">0</span>, <span class="at">nrow =</span> <span class="fu">nrow</span>(x_all), <span class="at">ncol =</span> <span class="fu">length</span>(feat_cols), <span class="at">sparse =</span> <span class="cn">TRUE</span>)</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(x_all_aligned) <span class="ot">&lt;-</span> feat_cols</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>common <span class="ot">&lt;-</span> <span class="fu">intersect</span>(feat_cols, <span class="fu">colnames</span>(x_all))</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>x_all_aligned[, common] <span class="ot">&lt;-</span> x_all[, common]</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilidades globales y etiquetas con 0.5</span></span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>prob_logit_all <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">predict</span>(cvfit, <span class="at">newx =</span> x_all_aligned, <span class="at">s =</span> cvfit<span class="sc">$</span>lambda.min, <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> summary(prob_logit_all):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 summary(prob_logit_all):</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(prob_logit_all))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
0.001020 0.003031 0.003031 0.132145 0.010625 1.000000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>matriz_dfm<span class="sc">$</span>modelo_logistico <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(prob_logit_all <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">"spam"</span>, <span class="st">"ham"</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> Distribución de predicciones del modelo logístico (global):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Distribución de predicciones del modelo logístico (global):</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(matriz_dfm<span class="sc">$</span>modelo_logistico))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 ham spam 
4841  731 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="st">"spam"</span> <span class="sc">%in%</span> <span class="fu">names</span>(matriz_dfm)) {</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> Vista previa etiquetas reales vs predichas:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">head</span>(matriz_dfm[, <span class="fu">c</span>(<span class="st">"spam"</span>, <span class="st">"modelo_logistico"</span>)]))</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">ℹ  'matriz_dfm' no contiene 'spam'; se omite la comparación real vs. pred.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Vista previa etiquetas reales vs predichas:
  spam modelo_logistico
1  ham              ham
2  ham              ham
3 spam             spam
4  ham              ham
5  ham              ham
6 spam             spam</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reordenar columnas: spam, modelo_logistico, modelo_SVM al inicio</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar que las columnas existen antes de reordenar</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>cols_principales <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"spam"</span>, <span class="st">"modelo_logistico"</span>, <span class="st">"modelo_SVM"</span>)</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar solo las columnas que realmente existen</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>cols_principales <span class="ot">&lt;-</span> cols_principales[cols_principales <span class="sc">%in%</span> <span class="fu">names</span>(matriz_dfm)]</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear nuevo orden: las principales primero + todas las demás después</span></span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>nuevo_orden <span class="ot">&lt;-</span> <span class="fu">c</span>(cols_principales, <span class="fu">setdiff</span>(<span class="fu">names</span>(matriz_dfm), cols_principales))</span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar el nuevo orden de columnas</span></span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a>matriz_dfm <span class="ot">&lt;-</span> matriz_dfm[, nuevo_orden]</span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-16"><a href="#cb71-16" aria-hidden="true" tabindex="-1"></a><span class="co">#Comprobación rápida</span></span>
<span id="cb71-17"><a href="#cb71-17" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> Columnas al inicio del dataframe:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Columnas al inicio del dataframe:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(<span class="fu">names</span>(matriz_dfm), <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "spam"             "modelo_logistico" "modelo_SVM"       "doc_id"          
 [5] "go"               "jurong"           "point"            "crazy"           
 [9] "available"        "bugis"           </code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> Vista previa:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Vista previa:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(matriz_dfm[, cols_principales]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  spam modelo_logistico modelo_SVM
1  ham              ham        ham
2  ham              ham        ham
3 spam             spam       spam
4  ham              ham        ham
5  ham              ham        ham
6 spam             spam       spam</code></pre>
</div>
</div>
</section>
</section>
<section id="problema-1" class="level1">
<h1>PROBLEMA 1:</h1>
<p>Crear un <strong>sistema</strong> que combine:</p>
<ul>
<li><p>las predicciones del <strong>SVM</strong> (modelo 1),</p></li>
<li><p>las predicciones del <strong>modelo logístico LASSO (glmnet)</strong> (modelo 2),</p></li>
<li><p>y la <strong>evidencia de palabras</strong> (top-k palabras “más spammy”) calculada desde frecuencias en el conjunto de entrenamiento.</p></li>
</ul>
<p>Calcularemos las <strong>sensibilidades y especificidades</strong> de cada modelo (a partir de la matriz de confusión en test_data).</p>
<p>Calcularemos la <strong>probabilidad de que ambos modelos alerten (positivos) dado que el email es spam</strong> (P(both + | spam)).</p>
<p>Usar <strong>Bayes</strong> para obtener P(spam | ambos modelos positivos).</p>
<p>Calcularemos la <strong>probabilidad posterior</strong> combinando además la <strong>evidencia de palabras</strong> (likelihood ratios de palabras características)</p>
<ol type="1">
<li>Sensibilidad y Especificidad modelo SVM</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">exists</span>(<span class="st">"conf_matrix_svm"</span>)) {</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  svm_se <span class="ot">&lt;-</span> conf_matrix_svm<span class="sc">$</span>byClass[<span class="st">"Sensitivity"</span>]</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  svm_sp <span class="ot">&lt;-</span> conf_matrix_svm<span class="sc">$</span>byClass[<span class="st">"Specificity"</span>]</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  svm_pred_test <span class="ot">&lt;-</span> <span class="fu">predict</span>(svm_model, <span class="at">newdata =</span> test_data)</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  cm_svm_test <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(svm_pred_test, test_data<span class="sc">$</span>spam, <span class="at">positive =</span> <span class="st">"spam"</span>)</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>  svm_se <span class="ot">&lt;-</span> cm_svm_test<span class="sc">$</span>byClass[<span class="st">"Sensitivity"</span>]</span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a>  svm_sp <span class="ot">&lt;-</span> cm_svm_test<span class="sc">$</span>byClass[<span class="st">"Specificity"</span>]</span>
<span id="cb79-9"><a href="#cb79-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Modelo SVM:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Modelo SVM:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Sensibilidad: %.4f</span><span class="sc">\n</span><span class="st">"</span>, svm_se))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sensibilidad: 0.8993</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Especificidad: %.4f</span><span class="sc">\n</span><span class="st">"</span>, svm_sp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Especificidad: 0.9969</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Sensibilidad y Especificidad modelo LOGISTICO</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>x_test <span class="ot">&lt;-</span> <span class="fu">as</span>(<span class="fu">as.matrix</span>(<span class="fu">sapply</span>(test_data[, feat_cols, <span class="at">drop =</span> <span class="cn">FALSE</span>], as.numeric)), <span class="st">"dgCMatrix"</span>)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>prob_logit_test <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">predict</span>(cvfit, <span class="at">newx =</span> x_test, <span class="at">s =</span> cvfit<span class="sc">$</span>lambda.min, <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>pred_logit_test <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(prob_logit_test <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">"spam"</span>, <span class="st">"ham"</span>)</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>cm_logit_test <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="fu">factor</span>(pred_logit_test, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"ham"</span>,<span class="st">"spam"</span>)),</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>                                 test_data<span class="sc">$</span>spam, <span class="at">positive =</span> <span class="st">"spam"</span>)</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>logit_se <span class="ot">&lt;-</span> cm_logit_test<span class="sc">$</span>byClass[<span class="st">"Sensitivity"</span>]</span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>logit_sp <span class="ot">&lt;-</span> cm_logit_test<span class="sc">$</span>byClass[<span class="st">"Specificity"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Modelo Logístico LASSO (glmnet):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Modelo Logístico LASSO (glmnet):</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Sensibilidad: %.4f</span><span class="sc">\n</span><span class="st">"</span>, logit_se))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sensibilidad: 0.8725</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Especificidad: %.4f</span><span class="sc">\n</span><span class="st">"</span>, logit_sp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Especificidad: 0.9959</code></pre>
</div>
</div>
<p>La <strong>sensibilidad</strong> indica la capacidad del modelo de <strong>detectar correctamente los correos spam</strong>. El <strong>SVM</strong> tiene una sensibilidad algo mayor (<strong>0.899</strong>) frente al modelo <strong>LASSO</strong> (<strong>0.8725</strong>) lo que significa que este primero detecta un poco más de spam que el segundo modelo. Esta difernecia es relevante cuando lo que queremos es minimizar los FN, es decir, spam que se cuela sin ser detectado.</p>
<p>La <strong>especificidad</strong> indica la capacidad de detectar correctamente los correos ham (!= spam) . Ambos modelos predicen este muy bien, así que casi nunca marcan un correo no spam como spam.</p>
<p>Ninguno de nuestros modelos alcanza un 1 en sensibilidad, por lo que <strong>no llega a detectar todos el spam</strong>, así que queremos ver si combinándolos se puede aumnetar la probabilidad de detectar correctamente estos correos.</p>
<p>Ahora calcularemos la probabilidad a priori de que un correo sea spam</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>pi_prior <span class="ot">&lt;-</span> <span class="fu">mean</span>(train_data<span class="sc">$</span>spam <span class="sc">==</span> <span class="st">"spam"</span>)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Probabildiad a priori:"</span>, pi_prior, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probabildiad a priori: 0.1341409 </code></pre>
</div>
</div>
<p>Esto significa que de mi conjutno de datos el 13.4% de los emails son spam, lo que es algo bajo (suele ser así, nos llegan muchos menos correos de spam que no spam)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Asumiendo independencia condicional entre modelos</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>p_both_pos_given_spam <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(svm_se) <span class="sc">*</span> <span class="fu">as.numeric</span>(logit_se)</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>p_both_pos_given_ham  <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">as.numeric</span>(svm_sp)) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">as.numeric</span>(logit_sp))</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a><span class="co"># LR conjunto (Likelihood Ratio)</span></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>LR_both <span class="ot">&lt;-</span> p_both_pos_given_spam <span class="sc">/</span> p_both_pos_given_ham</span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>prior_odds <span class="ot">&lt;-</span> pi_prior <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> pi_prior)</span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a>post_odds_both <span class="ot">&lt;-</span> prior_odds <span class="sc">*</span> LR_both</span>
<span id="cb95-10"><a href="#cb95-10" aria-hidden="true" tabindex="-1"></a><span class="co">#para llegar al cálculo de probabilidad posterior:</span></span>
<span id="cb95-11"><a href="#cb95-11" aria-hidden="true" tabindex="-1"></a>post_prob_both <span class="ot">&lt;-</span> post_odds_both <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> post_odds_both)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>probabilidad de que <strong>ambos</strong> modelos <strong>predigan “spam” siendo realmente spam:</strong></p>
<p>P(SVM+&nbsp;y&nbsp;LASSO+∣spam)=0.784</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">P(both + | spam):"</span>, p_both_pos_given_spam, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
P(both + | spam): 0.7846493 </code></pre>
</div>
</div>
<p>Esto refleja la <strong>capacidad conjunta de los modelos</strong> para detectar si un email es realmente spam, este valor de <strong>0.784</strong> indica que la combinación de modelos es bastante buena pero <strong>no perfecta</strong></p></li>
<li><p>Probabilidad de que <strong>ambos</strong> modelos <strong>digan “spam” de forma erronea</strong>, es decir, que digan que es <strong>“spam” siendo “ham”:</strong></p>
<p>P(SVM+&nbsp;y&nbsp;LASSO+∣ham)=0.0001</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(both + | ham):"</span>, p_both_pos_given_ham, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(both + | ham): 1.288625e-05 </code></pre>
</div>
</div>
<p>Aquí estamos reflejando los falsos positivos (FP) conjuntos. Aquí se hace muy buen trabajo si queremos minimizar esos falsos positivos, lo que indica que es muy <strong>raro</strong> que <strong>ambos</strong> modelos <strong>cometan un error simultáneamnte</strong></p></li>
<li><p>La <strong>Likelihood Ratio</strong> conjunta (LR) mide c<strong>uánto más probable</strong> es que <strong>ambos</strong> modelos <strong>digan si el correo es spam siendo ham:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Likelihood Ratio tgh:"</span>, LR_both, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood Ratio tgh: 60890.42 </code></pre>
</div>
</div></li>
<li><p><strong>Probabilidad posterior</strong>, es decir, la probabilidad de que un correo <strong>sea</strong> realmente <strong>spam</strong> <strong>después</strong> de observar que <strong>ambos</strong> <strong>dicen que sí es spam:</strong></p>
<p>P(spam∣SVM+&nbsp;y&nbsp;LASSO+)=0.9998</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(spam | both +):"</span>, post_prob_both, <span class="st">"</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(spam | both +): 0.999894 </code></pre>
</div>
</div>
<p>Este resultado refleja que la <strong>combinación</strong> de modelos es muy <strong>confiable</strong></p></li>
</ul>
<p>Calculo de probabilidades posteriores individuales, es decfir, para cada modelo por separado</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>LR_svm <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(svm_se) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">as.numeric</span>(svm_sp))</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>LR_logit <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(logit_se) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">as.numeric</span>(logit_sp))</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>post_odds_svm <span class="ot">&lt;-</span> prior_odds <span class="sc">*</span> LR_svm</span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>post_prob_svm <span class="ot">&lt;-</span> post_odds_svm <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> post_odds_svm)</span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a>post_odds_logit <span class="ot">&lt;-</span> prior_odds <span class="sc">*</span> LR_logit</span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a>post_prob_logit <span class="ot">&lt;-</span> post_odds_logit <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> post_odds_logit)</span>
<span id="cb104-9"><a href="#cb104-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-10"><a href="#cb104-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(spam | SVM +):"</span>, post_prob_svm, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(spam | SVM +): 0.9781738 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(spam | Logit +):"</span>, post_prob_logit, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(spam | Logit +): 0.9702461 </code></pre>
</div>
</div>
<ul>
<li><p>La probabilidad de que un correo sea realmente spam si el SVM predice spam es de 0.9782</p></li>
<li><p>La probabilidad de que un correo sea realmnete spam si el modelo logístico predice spam es de 0.9702</p></li>
</ul>
<p>Identificamos las <strong>palabras</strong> más “<strong>spammy</strong>”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculamos P(word|spam) y P(word|ham) desde train_data</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="co"># feat_cols ya son las columnas de token/word (0/1 o counts)</span></span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">20</span>   <span class="co"># top-k palabras a usar como evidencia</span></span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a><span class="co">#separamos los correos por clase</span></span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a>train_spam_idx <span class="ot">&lt;-</span> <span class="fu">which</span>(train_data<span class="sc">$</span>spam <span class="sc">==</span> <span class="st">"spam"</span>)</span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>train_ham_idx  <span class="ot">&lt;-</span> <span class="fu">which</span>(train_data<span class="sc">$</span>spam <span class="sc">==</span> <span class="st">"ham"</span>)</span>
<span id="cb108-7"><a href="#cb108-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-8"><a href="#cb108-8" aria-hidden="true" tabindex="-1"></a><span class="co">#contamos cuántas veces aparece cada palabra</span></span>
<span id="cb108-9"><a href="#cb108-9" aria-hidden="true" tabindex="-1"></a>spam_counts <span class="ot">&lt;-</span> <span class="fu">colSums</span>(train_data[train_spam_idx, feat_cols, <span class="at">drop =</span> <span class="cn">FALSE</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb108-10"><a href="#cb108-10" aria-hidden="true" tabindex="-1"></a>ham_counts  <span class="ot">&lt;-</span> <span class="fu">colSums</span>(train_data[train_ham_idx,  feat_cols, <span class="at">drop =</span> <span class="cn">FALSE</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb108-11"><a href="#cb108-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-12"><a href="#cb108-12" aria-hidden="true" tabindex="-1"></a><span class="co">#tamaño</span></span>
<span id="cb108-13"><a href="#cb108-13" aria-hidden="true" tabindex="-1"></a>N_spam_docs <span class="ot">&lt;-</span> <span class="fu">length</span>(train_spam_idx)</span>
<span id="cb108-14"><a href="#cb108-14" aria-hidden="true" tabindex="-1"></a>N_ham_docs  <span class="ot">&lt;-</span> <span class="fu">length</span>(train_ham_idx)</span>
<span id="cb108-15"><a href="#cb108-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-16"><a href="#cb108-16" aria-hidden="true" tabindex="-1"></a><span class="co">#calculamos las probbailidades condicionadas </span></span>
<span id="cb108-17"><a href="#cb108-17" aria-hidden="true" tabindex="-1"></a><span class="co">#P(word|spam): probbailidad de encontrar esa palabra si es spam </span></span>
<span id="cb108-18"><a href="#cb108-18" aria-hidden="true" tabindex="-1"></a><span class="co">#P(word|ham): probabilidad de encontrar esa palabra si el correo es ham</span></span>
<span id="cb108-19"><a href="#cb108-19" aria-hidden="true" tabindex="-1"></a>p_word_given_spam <span class="ot">&lt;-</span> (spam_counts <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> (<span class="fu">sum</span>(spam_counts) <span class="sc">+</span> <span class="fu">length</span>(feat_cols))</span>
<span id="cb108-20"><a href="#cb108-20" aria-hidden="true" tabindex="-1"></a>p_word_given_ham  <span class="ot">&lt;-</span> (ham_counts  <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> (<span class="fu">sum</span>(ham_counts)  <span class="sc">+</span> <span class="fu">length</span>(feat_cols))</span>
<span id="cb108-21"><a href="#cb108-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-22"><a href="#cb108-22" aria-hidden="true" tabindex="-1"></a><span class="co">#LR por palabra y ordenar las más "spammy"</span></span>
<span id="cb108-23"><a href="#cb108-23" aria-hidden="true" tabindex="-1"></a>lr_words <span class="ot">&lt;-</span> p_word_given_spam <span class="sc">/</span> p_word_given_ham</span>
<span id="cb108-24"><a href="#cb108-24" aria-hidden="true" tabindex="-1"></a>topk <span class="ot">&lt;-</span> <span class="fu">sort</span>(lr_words, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span>k]</span>
<span id="cb108-25"><a href="#cb108-25" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Top-k palabras con mayor LR (spam/ham):</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Top-k palabras con mayor LR (spam/ham):</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(topk, k))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     claim      prize        won          å       tone       150p guaranteed 
 207.23158  164.89394  135.92609  133.14072  124.78461  118.09972   84.67527 
        cs    awarded     150ppm   ringtone        mob      tones collection 
  75.76208   64.62060   64.62060   62.39230   51.25082   49.02252   49.02252 
     valid      nokia        10p      games     weekly       poly 
  46.79423   46.79423   44.56593   42.33763   42.33763   42.33763 </code></pre>
</div>
</div>
<p>Lo que conseguimos con esto es ver qu<strong>é palabras son las que mas dicen si un correo es spam</strong>. Estas serían las 20 palabras con mayor LR entre los correos spam y ham. Las palabras están relacionadas con premios/recompensas, ofertas/promociones o cosas de telefonía. Por lo que concluimos que los <strong>correos de spam tienen un patrón temático</strong> muy claro. Por ello la presencia de estas palabras aumentan frecuentemente la probabilidad posterior de spam.</p>
<p>Lo que haremos ahora es clacular la LR basadas en las palabras que realmente aparecen en un email concreto.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>i <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>words_present <span class="ot">&lt;-</span> feat_cols[ <span class="fu">which</span>(<span class="fu">as.numeric</span>(test_data[i, feat_cols]) <span class="sc">&gt;</span> <span class="dv">0</span>) ]</span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a>lr_obs <span class="ot">&lt;-</span> <span class="fu">prod</span>(lr_words[<span class="fu">intersect</span>(<span class="fu">names</span>(lr_words), words_present)])</span>
<span id="cb112-6"><a href="#cb112-6" aria-hidden="true" tabindex="-1"></a>log_lr_obs <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">log</span>(lr_words[<span class="fu">intersect</span>(<span class="fu">names</span>(lr_words), words_present)]), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb112-7"><a href="#cb112-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb112-8"><a href="#cb112-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">LR (palabras) observadas en test["</span>, i, <span class="st">"]:"</span>, lr_obs, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
LR (palabras) observadas en test[ 1 ]: 20.89579 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"log LR (palabras):"</span>, log_lr_obs, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>log LR (palabras): 3.039548 </code></pre>
</div>
</div>
<p>La LR del conjunto de palabras que aparecen en el correo de prueba número 1 es de 20.89, lo que significa que las palabras en este correo son unas <strong>21 veces más probables si el correo es spam que si es ham.</strong></p>
<p>En este último paso <strong>sumamos</strong> la <strong>evidencia de palabras</strong> a la c<strong>ombinación de los dos modelos</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="co"># log prior odds</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>log_prior_odds <span class="ot">&lt;-</span> <span class="fu">log</span>(prior_odds)</span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>log_lr_models <span class="ot">&lt;-</span> <span class="fu">log</span>(LR_both) <span class="co"># si quieres LR de ambos</span></span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a><span class="co"># total log posterior odds:</span></span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>log_post_total <span class="ot">&lt;-</span> log_prior_odds <span class="sc">+</span> log_lr_models <span class="sc">+</span> log_lr_obs</span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a>post_prob_total <span class="ot">&lt;-</span> <span class="fu">exp</span>(log_post_total) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(log_post_total))</span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-8"><a href="#cb116-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">P(spam | SVM+ &amp; Logit+ &amp; palabras_observadas):"</span>, post_prob_total, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
P(spam | SVM+ &amp; Logit+ &amp; palabras_observadas): 0.9999949 </code></pre>
</div>
</div>
<p>El resultado de 0.999 es la probabilidad posterior calculada con el teorema de Bayes<strong>, P(spam|ambos modelos + palabras)</strong></p>
</section>
<section id="probelma-2" class="level1">
<h1>PROBELMA 2:</h1>
<p>Evaluación comparativa de la coherencia bayesiana y la calibración probabilística entre modelos de Regresión Logística (LASSO) y SVM en la detección de mensajes spam:El presente análisis tuvo como objetivo determinar qué modelo —Regresión Logística (LASSO) o SVM— produce probabilidades más coherentes con el teorema de Bayes, es decir, qué modelo está mejor calibrado bayesianamente en la tarea de clasificar mensajes como <em>spam</em> o <em>no spam</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="co">#COMPARACIÓN BAYESIANA ENTRE MODELO LOGÍSTICO Y SVM</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">exists</span>(<span class="st">"svm_model"</span>)) {</span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Probabilidades SVM</span></span>
<span id="cb118-6"><a href="#cb118-6" aria-hidden="true" tabindex="-1"></a>  pred_svm_obj <span class="ot">&lt;-</span> <span class="fu">predict</span>(svm_model, <span class="at">newdata =</span> matriz_dfm, <span class="at">probability =</span> <span class="cn">TRUE</span>)</span>
<span id="cb118-7"><a href="#cb118-7" aria-hidden="true" tabindex="-1"></a>  probs_attr <span class="ot">&lt;-</span> <span class="fu">attr</span>(pred_svm_obj, <span class="st">"probabilities"</span>)</span>
<span id="cb118-8"><a href="#cb118-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-9"><a href="#cb118-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.null</span>(probs_attr)) {</span>
<span id="cb118-10"><a href="#cb118-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">"El modelo SVM no fue entrenado con probability = TRUE."</span>)</span>
<span id="cb118-11"><a href="#cb118-11" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb118-12"><a href="#cb118-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="st">"spam"</span> <span class="sc">%in%</span> <span class="fu">colnames</span>(probs_attr)) {</span>
<span id="cb118-13"><a href="#cb118-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">"La matriz de probabilidades SVM no contiene la columna 'spam'."</span>)</span>
<span id="cb118-14"><a href="#cb118-14" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb118-15"><a href="#cb118-15" aria-hidden="true" tabindex="-1"></a>  prob_svm_all <span class="ot">&lt;-</span> probs_attr[, <span class="st">"spam"</span>]</span>
<span id="cb118-16"><a href="#cb118-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-17"><a href="#cb118-17" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Dataframe conjunto</span></span>
<span id="cb118-18"><a href="#cb118-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stopifnot</span>(<span class="st">"spam"</span> <span class="sc">%in%</span> <span class="fu">names</span>(matriz_dfm))</span>
<span id="cb118-19"><a href="#cb118-19" aria-hidden="true" tabindex="-1"></a>  df_all <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb118-20"><a href="#cb118-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">spam_real  =</span> matriz_dfm<span class="sc">$</span>spam,</span>
<span id="cb118-21"><a href="#cb118-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob_logit =</span> prob_logit_all,</span>
<span id="cb118-22"><a href="#cb118-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob_svm   =</span> prob_svm_all</span>
<span id="cb118-23"><a href="#cb118-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb118-24"><a href="#cb118-24" aria-hidden="true" tabindex="-1"></a>  df_all<span class="sc">$</span>spam_num <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df_all<span class="sc">$</span>spam_real <span class="sc">==</span> <span class="st">"spam"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb118-25"><a href="#cb118-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-26"><a href="#cb118-26" aria-hidden="true" tabindex="-1"></a>  <span class="co">#AUC </span></span>
<span id="cb118-27"><a href="#cb118-27" aria-hidden="true" tabindex="-1"></a>  roc_logit <span class="ot">&lt;-</span> pROC<span class="sc">::</span><span class="fu">roc</span>(df_all<span class="sc">$</span>spam_num, df_all<span class="sc">$</span>prob_logit)</span>
<span id="cb118-28"><a href="#cb118-28" aria-hidden="true" tabindex="-1"></a>  roc_svm   <span class="ot">&lt;-</span> pROC<span class="sc">::</span><span class="fu">roc</span>(df_all<span class="sc">$</span>spam_num, df_all<span class="sc">$</span>prob_svm)</span>
<span id="cb118-29"><a href="#cb118-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-30"><a href="#cb118-30" aria-hidden="true" tabindex="-1"></a>  auc_logit <span class="ot">&lt;-</span> <span class="fu">round</span>(pROC<span class="sc">::</span><span class="fu">auc</span>(roc_logit), <span class="dv">4</span>)</span>
<span id="cb118-31"><a href="#cb118-31" aria-hidden="true" tabindex="-1"></a>  auc_svm   <span class="ot">&lt;-</span> <span class="fu">round</span>(pROC<span class="sc">::</span><span class="fu">auc</span>(roc_svm), <span class="dv">4</span>)</span>
<span id="cb118-32"><a href="#cb118-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-33"><a href="#cb118-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> AUC Logístico:"</span>, auc_logit, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-34"><a href="#cb118-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">" AUC SVM:       "</span>, auc_svm, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-35"><a href="#cb118-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-36"><a href="#cb118-36" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Brier Score</span></span>
<span id="cb118-37"><a href="#cb118-37" aria-hidden="true" tabindex="-1"></a>  brier_logit <span class="ot">&lt;-</span> <span class="fu">mean</span>((df_all<span class="sc">$</span>spam_num <span class="sc">-</span> df_all<span class="sc">$</span>prob_logit)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb118-38"><a href="#cb118-38" aria-hidden="true" tabindex="-1"></a>  brier_svm   <span class="ot">&lt;-</span> <span class="fu">mean</span>((df_all<span class="sc">$</span>spam_num <span class="sc">-</span> df_all<span class="sc">$</span>prob_svm)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb118-39"><a href="#cb118-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Brier Logit:"</span>, <span class="fu">round</span>(brier_logit, <span class="dv">4</span>), <span class="st">" | Brier SVM:"</span>, <span class="fu">round</span>(brier_svm, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-40"><a href="#cb118-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-41"><a href="#cb118-41" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Calibración bayesiana por bins</span></span>
<span id="cb118-42"><a href="#cb118-42" aria-hidden="true" tabindex="-1"></a>  df_calib <span class="ot">&lt;-</span> df_all <span class="sc">%&gt;%</span></span>
<span id="cb118-43"><a href="#cb118-43" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">bin_logit =</span> <span class="fu">cut</span>(prob_logit, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.1</span>), <span class="at">include.lowest =</span> <span class="cn">TRUE</span>),</span>
<span id="cb118-44"><a href="#cb118-44" aria-hidden="true" tabindex="-1"></a>           <span class="at">bin_svm   =</span> <span class="fu">cut</span>(prob_svm,   <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.1</span>), <span class="at">include.lowest =</span> <span class="cn">TRUE</span>))</span>
<span id="cb118-45"><a href="#cb118-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-46"><a href="#cb118-46" aria-hidden="true" tabindex="-1"></a>  calib_logit <span class="ot">&lt;-</span> df_calib <span class="sc">%&gt;%</span></span>
<span id="cb118-47"><a href="#cb118-47" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(bin_logit) <span class="sc">%&gt;%</span></span>
<span id="cb118-48"><a href="#cb118-48" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">prob_media =</span> <span class="fu">mean</span>(prob_logit),</span>
<span id="cb118-49"><a href="#cb118-49" aria-hidden="true" tabindex="-1"></a>              <span class="at">spam_real =</span> <span class="fu">mean</span>(spam_num),</span>
<span id="cb118-50"><a href="#cb118-50" aria-hidden="true" tabindex="-1"></a>              <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb118-51"><a href="#cb118-51" aria-hidden="true" tabindex="-1"></a>              <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb118-52"><a href="#cb118-52" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(prob_media)</span>
<span id="cb118-53"><a href="#cb118-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-54"><a href="#cb118-54" aria-hidden="true" tabindex="-1"></a>  calib_svm <span class="ot">&lt;-</span> df_calib <span class="sc">%&gt;%</span></span>
<span id="cb118-55"><a href="#cb118-55" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(bin_svm) <span class="sc">%&gt;%</span></span>
<span id="cb118-56"><a href="#cb118-56" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">prob_media =</span> <span class="fu">mean</span>(prob_svm),</span>
<span id="cb118-57"><a href="#cb118-57" aria-hidden="true" tabindex="-1"></a>              <span class="at">spam_real =</span> <span class="fu">mean</span>(spam_num),</span>
<span id="cb118-58"><a href="#cb118-58" aria-hidden="true" tabindex="-1"></a>              <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb118-59"><a href="#cb118-59" aria-hidden="true" tabindex="-1"></a>              <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb118-60"><a href="#cb118-60" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(prob_media)</span>
<span id="cb118-61"><a href="#cb118-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-62"><a href="#cb118-62" aria-hidden="true" tabindex="-1"></a>  <span class="co">#ECE y MCE </span></span>
<span id="cb118-63"><a href="#cb118-63" aria-hidden="true" tabindex="-1"></a>  ECE <span class="ot">&lt;-</span> <span class="cf">function</span>(calib) {</span>
<span id="cb118-64"><a href="#cb118-64" aria-hidden="true" tabindex="-1"></a>    w <span class="ot">&lt;-</span> calib<span class="sc">$</span>n <span class="sc">/</span> <span class="fu">sum</span>(calib<span class="sc">$</span>n)</span>
<span id="cb118-65"><a href="#cb118-65" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum</span>(w <span class="sc">*</span> <span class="fu">abs</span>(calib<span class="sc">$</span>spam_real <span class="sc">-</span> calib<span class="sc">$</span>prob_media))</span>
<span id="cb118-66"><a href="#cb118-66" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb118-67"><a href="#cb118-67" aria-hidden="true" tabindex="-1"></a>  MCE <span class="ot">&lt;-</span> <span class="cf">function</span>(calib) <span class="fu">max</span>(<span class="fu">abs</span>(calib<span class="sc">$</span>spam_real <span class="sc">-</span> calib<span class="sc">$</span>prob_media))</span>
<span id="cb118-68"><a href="#cb118-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-69"><a href="#cb118-69" aria-hidden="true" tabindex="-1"></a>  ece_logit <span class="ot">&lt;-</span> <span class="fu">ECE</span>(calib_logit)</span>
<span id="cb118-70"><a href="#cb118-70" aria-hidden="true" tabindex="-1"></a>  ece_svm   <span class="ot">&lt;-</span> <span class="fu">ECE</span>(calib_svm)</span>
<span id="cb118-71"><a href="#cb118-71" aria-hidden="true" tabindex="-1"></a>  mce_logit <span class="ot">&lt;-</span> <span class="fu">MCE</span>(calib_logit)</span>
<span id="cb118-72"><a href="#cb118-72" aria-hidden="true" tabindex="-1"></a>  mce_svm   <span class="ot">&lt;-</span> <span class="fu">MCE</span>(calib_svm)</span>
<span id="cb118-73"><a href="#cb118-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-74"><a href="#cb118-74" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"ECE Logit:"</span>, <span class="fu">round</span>(ece_logit, <span class="dv">4</span>), <span class="st">" | ECE SVM:"</span>, <span class="fu">round</span>(ece_svm, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-75"><a href="#cb118-75" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"MCE Logit:"</span>, <span class="fu">round</span>(mce_logit, <span class="dv">4</span>), <span class="st">" | MCE SVM:"</span>, <span class="fu">round</span>(mce_svm, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-76"><a href="#cb118-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-77"><a href="#cb118-77" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Gráficos de calibración bayesiana </span></span>
<span id="cb118-78"><a href="#cb118-78" aria-hidden="true" tabindex="-1"></a>  plot_logit <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(calib_logit, <span class="fu">aes</span>(<span class="at">x =</span> prob_media, <span class="at">y =</span> spam_real)) <span class="sc">+</span></span>
<span id="cb118-79"><a href="#cb118-79" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb118-80"><a href="#cb118-80" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb118-81"><a href="#cb118-81" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray40"</span>) <span class="sc">+</span></span>
<span id="cb118-82"><a href="#cb118-82" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">" Calibración Bayesiana - Regresión Logística"</span>,</span>
<span id="cb118-83"><a href="#cb118-83" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Probabilidad predicha de Spam"</span>,</span>
<span id="cb118-84"><a href="#cb118-84" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Proporción real de Spam"</span>) <span class="sc">+</span></span>
<span id="cb118-85"><a href="#cb118-85" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">13</span>)</span>
<span id="cb118-86"><a href="#cb118-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-87"><a href="#cb118-87" aria-hidden="true" tabindex="-1"></a>  plot_svm <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(calib_svm, <span class="fu">aes</span>(<span class="at">x =</span> prob_media, <span class="at">y =</span> spam_real)) <span class="sc">+</span></span>
<span id="cb118-88"><a href="#cb118-88" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb118-89"><a href="#cb118-89" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb118-90"><a href="#cb118-90" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray40"</span>) <span class="sc">+</span></span>
<span id="cb118-91"><a href="#cb118-91" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Calibración Bayesiana - SVM"</span>,</span>
<span id="cb118-92"><a href="#cb118-92" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Probabilidad predicha de Spam"</span>,</span>
<span id="cb118-93"><a href="#cb118-93" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">"Proporción real de Spam"</span>) <span class="sc">+</span></span>
<span id="cb118-94"><a href="#cb118-94" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">13</span>)</span>
<span id="cb118-95"><a href="#cb118-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-96"><a href="#cb118-96" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Arreglo: dos columnas y título con annotate_figure/text_grob</span></span>
<span id="cb118-97"><a href="#cb118-97" aria-hidden="true" tabindex="-1"></a>  comparacion_calibracion <span class="ot">&lt;-</span> ggpubr<span class="sc">::</span><span class="fu">ggarrange</span>(</span>
<span id="cb118-98"><a href="#cb118-98" aria-hidden="true" tabindex="-1"></a>    plot_logit, plot_svm,</span>
<span id="cb118-99"><a href="#cb118-99" aria-hidden="true" tabindex="-1"></a>    <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>,</span>
<span id="cb118-100"><a href="#cb118-100" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>),</span>
<span id="cb118-101"><a href="#cb118-101" aria-hidden="true" tabindex="-1"></a>    <span class="at">common.legend =</span> <span class="cn">FALSE</span></span>
<span id="cb118-102"><a href="#cb118-102" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb118-103"><a href="#cb118-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-104"><a href="#cb118-104" aria-hidden="true" tabindex="-1"></a>  comparacion_calibracion <span class="ot">&lt;-</span> ggpubr<span class="sc">::</span><span class="fu">annotate_figure</span>(</span>
<span id="cb118-105"><a href="#cb118-105" aria-hidden="true" tabindex="-1"></a>    comparacion_calibracion,</span>
<span id="cb118-106"><a href="#cb118-106" aria-hidden="true" tabindex="-1"></a>    <span class="at">top =</span> ggpubr<span class="sc">::</span><span class="fu">text_grob</span>(</span>
<span id="cb118-107"><a href="#cb118-107" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Comparación de calibración bayesiana entre modelos"</span>,</span>
<span id="cb118-108"><a href="#cb118-108" aria-hidden="true" tabindex="-1"></a>      <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span></span>
<span id="cb118-109"><a href="#cb118-109" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb118-110"><a href="#cb118-110" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb118-111"><a href="#cb118-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-112"><a href="#cb118-112" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(comparacion_calibracion)</span>
<span id="cb118-113"><a href="#cb118-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-114"><a href="#cb118-114" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Desviación media de calibración</span></span>
<span id="cb118-115"><a href="#cb118-115" aria-hidden="true" tabindex="-1"></a>  desv_logit <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(calib_logit<span class="sc">$</span>spam_real <span class="sc">-</span> calib_logit<span class="sc">$</span>prob_media), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb118-116"><a href="#cb118-116" aria-hidden="true" tabindex="-1"></a>  desv_svm   <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(calib_svm<span class="sc">$</span>spam_real   <span class="sc">-</span> calib_svm<span class="sc">$</span>prob_media),   <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb118-117"><a href="#cb118-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-118"><a href="#cb118-118" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> Desviación media de calibración (|obs - pred|):</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-119"><a href="#cb118-119" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"   Logístico:"</span>, <span class="fu">round</span>(desv_logit, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-120"><a href="#cb118-120" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"   SVM:      "</span>, <span class="fu">round</span>(desv_svm, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-121"><a href="#cb118-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-122"><a href="#cb118-122" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Conclusión final</span></span>
<span id="cb118-123"><a href="#cb118-123" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> CONCLUSIÓN FINAL:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-124"><a href="#cb118-124" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (desv_logit <span class="sc">&lt;</span> desv_svm <span class="sc">&amp;</span> ece_logit <span class="sc">&lt;</span> ece_svm) {</span>
<span id="cb118-125"><a href="#cb118-125" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"  El modelo LOGÍSTICO presenta mejor calibración bayesiana (más coherente con P(Spam|Modelo)).</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-126"><a href="#cb118-126" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (desv_logit <span class="sc">&gt;</span> desv_svm <span class="sc">&amp;</span> ece_logit <span class="sc">&gt;</span> ece_svm) {</span>
<span id="cb118-127"><a href="#cb118-127" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"El modelo SVM produce probabilidades más coherentes con el teorema de Bayes.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-128"><a href="#cb118-128" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb118-129"><a href="#cb118-129" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Ambos modelos presentan un rendimiento bayesiano similar.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-130"><a href="#cb118-130" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb118-131"><a href="#cb118-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-132"><a href="#cb118-132" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb118-133"><a href="#cb118-133" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> No existe 'svm_model' en el entorno. Se omite la comparación.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb118-134"><a href="#cb118-134" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 AUC Logístico: 0.9939 
 AUC SVM:        0.9972 
Brier Logit: 0.0046  | Brier SVM: 0.0033 
ECE Logit: 0.009  | ECE SVM: 0.0048 
MCE Logit: 0.2659  | MCE SVM: 0.3121 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Bayesian_Evidence_Aggegation_for_Spam_Detection_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Desviación media de calibración (|obs - pred|):
   Logístico: 0.1293 
   SVM:       0.1104 

 CONCLUSIÓN FINAL:
El modelo SVM produce probabilidades más coherentes con el teorema de Bayes.</code></pre>
</div>
</div>
<p>El presente análisis tiene como objetivo determinar <strong>qué modelo —Regresión Logística (LASSO) o SVM— produce probabilidades más coherentes con el teorema de Bayes</strong>, es decir, cuál de ellos presenta <strong>una calibración bayesiana más precisa</strong> en la tarea de clasificar mensajes como <em>spam</em> o <em>no spam</em>.</p>
<p>Desde una perspectiva bayesiana, un modelo se considera bien calibrado cuando las probabilidades que estima coinciden con las frecuencias reales observadas. En otras palabras, se cumple empíricamente la relación P(Spam∣Modelo)≈P(Spam&nbsp;real). Esto significa que, si el modelo predice una probabilidad de 0.8 de que un mensaje sea <em>spam</em>, aproximadamente el 80 % de los correos con esa probabilidad deberían ser realmente <em>spam</em>.</p>
<p>Para evaluar esta coherencia bayesiana, se compararon ambos modelos mediante tres tipos de indicadores: <strong>capacidad discriminante (AUC)</strong>, <strong>precisión probabilística (Brier Score)</strong> y <strong>errores de calibración (ECE y MCE)</strong>.</p>
<p>En primer lugar, la <strong>capacidad discriminante</strong>, medida con el AUC, fue muy alta para ambos modelos: <strong>AUC Logístico = 0.9939</strong> y <strong>AUC SVM = 0.9972</strong>. Ambos clasifican con una precisión casi perfecta entre correos <em>spam</em> y <em>no spam</em>, aunque el <strong>SVM obtiene un valor ligeramente superior</strong>, lo que indica una mejor capacidad para distinguir entre ambas clases.</p>
<p>En segundo lugar, la <strong>precisión probabilística</strong>, evaluada mediante el <em>Brier Score</em>, fue de <strong>0.0046 para el modelo Logístico</strong> y <strong>0.0033 para el SVM</strong>. Como valores más bajos indican mayor exactitud, el <strong>SVM muestra una correspondencia más fiel entre las probabilidades predichas y los resultados reales</strong>, reflejando una mayor coherencia con la frecuencia observada de <em>spam</em>.</p>
<p>En cuanto a la <strong>calibración bayesiana</strong>, se analizaron los errores <strong>ECE (Expected Calibration Error)</strong> y <strong>MCE (Max Calibration Error)</strong>. El <strong>ECE</strong>, que mide el error medio ponderado entre la probabilidad estimada y la proporción real observada, fue menor para el SVM (<strong>0.0048</strong>) que para el Logístico (<strong>0.0090</strong>), indicando que el <strong>SVM está mejor calibrado en promedio</strong>. En cambio, el <strong>MCE</strong>, que refleja la desviación máxima, fue ligeramente mejor para el Logístico (<strong>0.2659</strong> frente a <strong>0.3121</strong>), lo que sugiere que el Logístico mantiene un comportamiento algo más estable en los extremos de probabilidad, aunque la diferencia es mínima.</p>
<p>Los <strong>gráficos de calibración bayesiana</strong> muestran visualmente esta relación. En ellos, la línea diagonal discontinua (y = x) representa la calibración perfecta. El <strong>modelo Logístico</strong> tiende a subestimar ligeramente la probabilidad de <em>spam</em> en los niveles intermedios, mientras que el <strong>SVM sigue la diagonal con mayor fidelidad</strong>, ajustándose mejor a la probabilidad real de <em>spam</em>.</p>
</section>
<section id="problema-3" class="level1">
<h1>PROBLEMA 3:</h1>
<p>Análisis Bayesiano Detallado de la Influencia Léxica en la Clasificación de Mensajes Spam y No Spam:</p>
<ul>
<li><p>Estimación de Probabilidades Condicionales P(Spam∣Palabra)</p></li>
<li><p>Identificación de Palabras Discriminativas</p></li>
<li><p>Evaluación del Impacto de la Frecuencia Léxica en la Inferencia Posterior</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>matriz_dfm <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(matriz_dfm)</span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a><span class="co">#matriz_dfm$spam &lt;- as.numeric(as.character(matriz_dfm$spam))</span></span>
<span id="cb125-4"><a href="#cb125-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-5"><a href="#cb125-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-6"><a href="#cb125-6" aria-hidden="true" tabindex="-1"></a>matriz_dfm<span class="sc">$</span>spam <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(matriz_dfm<span class="sc">$</span>spam <span class="sc">==</span> <span class="st">"spam"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb125-7"><a href="#cb125-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-8"><a href="#cb125-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-9"><a href="#cb125-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Conteo de clases:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Conteo de clases:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(matriz_dfm<span class="sc">$</span>spam))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1 
4825  747 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>cols_no_texto <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"spam"</span>, <span class="st">"doc_id"</span>, <span class="st">"modelo_logistico"</span>, <span class="st">"modelo_SVM"</span>)</span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>word_cols <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="fu">names</span>(matriz_dfm), cols_no_texto)</span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-4"><a href="#cb129-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-5"><a href="#cb129-5" aria-hidden="true" tabindex="-1"></a>matriz_dfm[word_cols] <span class="ot">&lt;-</span> <span class="fu">lapply</span>(matriz_dfm[word_cols], <span class="cf">function</span>(x) <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(x)))</span>
<span id="cb129-6"><a href="#cb129-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-7"><a href="#cb129-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-8"><a href="#cb129-8" aria-hidden="true" tabindex="-1"></a>spam_docs <span class="ot">&lt;-</span> <span class="fu">subset</span>(matriz_dfm, spam <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb129-9"><a href="#cb129-9" aria-hidden="true" tabindex="-1"></a>nospam_docs <span class="ot">&lt;-</span> <span class="fu">subset</span>(matriz_dfm, spam <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb129-10"><a href="#cb129-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-11"><a href="#cb129-11" aria-hidden="true" tabindex="-1"></a>n_spam <span class="ot">&lt;-</span> <span class="fu">nrow</span>(spam_docs)</span>
<span id="cb129-12"><a href="#cb129-12" aria-hidden="true" tabindex="-1"></a>n_no_spam <span class="ot">&lt;-</span> <span class="fu">nrow</span>(nospam_docs)</span>
<span id="cb129-13"><a href="#cb129-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-14"><a href="#cb129-14" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (n_spam <span class="sc">==</span> <span class="dv">0</span> <span class="sc">|</span> n_no_spam <span class="sc">==</span> <span class="dv">0</span>) {</span>
<span id="cb129-15"><a href="#cb129-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"no hay ejemplos suficientes de spam o no spam para calcular probabilidades."</span>)</span>
<span id="cb129-16"><a href="#cb129-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb129-17"><a href="#cb129-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-18"><a href="#cb129-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-19"><a href="#cb129-19" aria-hidden="true" tabindex="-1"></a>P_spam <span class="ot">&lt;-</span> n_spam <span class="sc">/</span> (n_spam <span class="sc">+</span> n_no_spam)</span>
<span id="cb129-20"><a href="#cb129-20" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="dv">1</span>  </span>
<span id="cb129-21"><a href="#cb129-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-22"><a href="#cb129-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-23"><a href="#cb129-23" aria-hidden="true" tabindex="-1"></a>P_word_given_spam <span class="ot">&lt;-</span> (<span class="fu">colSums</span>(spam_docs[, word_cols] <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">+</span> alpha) <span class="sc">/</span> (n_spam <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> alpha)</span>
<span id="cb129-24"><a href="#cb129-24" aria-hidden="true" tabindex="-1"></a>P_word_given_no_spam <span class="ot">&lt;-</span> (<span class="fu">colSums</span>(nospam_docs[, word_cols] <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">+</span> alpha) <span class="sc">/</span> (n_no_spam <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> alpha)</span>
<span id="cb129-25"><a href="#cb129-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-26"><a href="#cb129-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-27"><a href="#cb129-27" aria-hidden="true" tabindex="-1"></a>top3_spam <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">sort</span>(P_word_given_spam, <span class="at">decreasing =</span> <span class="cn">TRUE</span>))[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb129-28"><a href="#cb129-28" aria-hidden="true" tabindex="-1"></a>bottom3_spam <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">sort</span>(P_word_given_spam, <span class="at">decreasing =</span> <span class="cn">FALSE</span>))[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb129-29"><a href="#cb129-29" aria-hidden="true" tabindex="-1"></a>top3_no_spam <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">sort</span>(P_word_given_no_spam, <span class="at">decreasing =</span> <span class="cn">TRUE</span>))[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb129-30"><a href="#cb129-30" aria-hidden="true" tabindex="-1"></a>bottom3_no_spam <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">sort</span>(P_word_given_no_spam, <span class="at">decreasing =</span> <span class="cn">FALSE</span>))[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb129-31"><a href="#cb129-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-32"><a href="#cb129-32" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Palabras más frecuentes en SPAM:"</span>, <span class="fu">paste</span>(top3_spam, <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Palabras más frecuentes en SPAM: call, å, now </code></pre>
</div>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Palabras menos frecuentes en SPAM:"</span>, <span class="fu">paste</span>(bottom3_spam, <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Palabras menos frecuentes en SPAM: jurong, point, bugis </code></pre>
</div>
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Palabras más frecuentes en NO SPAM:"</span>, <span class="fu">paste</span>(top3_no_spam, <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Palabras más frecuentes en NO SPAM: u, can, now </code></pre>
</div>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Palabras menos frecuentes en NO SPAM:"</span>, <span class="fu">paste</span>(bottom3_no_spam, <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Palabras menos frecuentes en NO SPAM: entry, wkly, fa </code></pre>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>P_word <span class="ot">&lt;-</span> P_word_given_spam <span class="sc">*</span> P_spam <span class="sc">+</span> P_word_given_no_spam <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> P_spam)</span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a>P_spam_given_word <span class="ot">&lt;-</span> (P_word_given_spam <span class="sc">*</span> P_spam) <span class="sc">/</span> P_word</span>
<span id="cb137-3"><a href="#cb137-3" aria-hidden="true" tabindex="-1"></a>efecto <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(P_spam_given_word <span class="sc">&gt;</span> P_spam, <span class="st">"Aumenta"</span>, <span class="st">"Reduce"</span>)</span>
<span id="cb137-4"><a href="#cb137-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-5"><a href="#cb137-5" aria-hidden="true" tabindex="-1"></a>resumen <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb137-6"><a href="#cb137-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">palabra =</span> word_cols,</span>
<span id="cb137-7"><a href="#cb137-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">P_spam_dado_palabra =</span> <span class="fu">round</span>(P_spam_given_word, <span class="dv">4</span>),</span>
<span id="cb137-8"><a href="#cb137-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">efecto =</span> efecto</span>
<span id="cb137-9"><a href="#cb137-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb137-10"><a href="#cb137-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-11"><a href="#cb137-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-12"><a href="#cb137-12" aria-hidden="true" tabindex="-1"></a>prob_spam_dado_3 <span class="ot">&lt;-</span> <span class="cf">function</span>(words) {</span>
<span id="cb137-13"><a href="#cb137-13" aria-hidden="true" tabindex="-1"></a>  p_w_spam <span class="ot">&lt;-</span> <span class="fu">prod</span>(P_word_given_spam[words])</span>
<span id="cb137-14"><a href="#cb137-14" aria-hidden="true" tabindex="-1"></a>  p_w_no_spam <span class="ot">&lt;-</span> <span class="fu">prod</span>(P_word_given_no_spam[words])</span>
<span id="cb137-15"><a href="#cb137-15" aria-hidden="true" tabindex="-1"></a>  (p_w_spam <span class="sc">*</span> P_spam) <span class="sc">/</span> (p_w_spam <span class="sc">*</span> P_spam <span class="sc">+</span> p_w_no_spam <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> P_spam))</span>
<span id="cb137-16"><a href="#cb137-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb137-17"><a href="#cb137-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-18"><a href="#cb137-18" aria-hidden="true" tabindex="-1"></a>P_spam_top3 <span class="ot">&lt;-</span> <span class="fu">prob_spam_dado_3</span>(top3_spam)</span>
<span id="cb137-19"><a href="#cb137-19" aria-hidden="true" tabindex="-1"></a>P_spam_bottom3 <span class="ot">&lt;-</span> <span class="fu">prob_spam_dado_3</span>(bottom3_spam)</span>
<span id="cb137-20"><a href="#cb137-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-21"><a href="#cb137-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-22"><a href="#cb137-22" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> INTERPRETACIÓN BAYESIANA:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 INTERPRETACIÓN BAYESIANA:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- P(Spam) global ="</span>, <span class="fu">round</span>(P_spam, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- P(Spam) global = 0.134 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- Si aparecen las 3 palabras más frecuentes de spam ("</span>, <span class="fu">paste</span>(top3_spam, <span class="at">collapse =</span> <span class="st">", "</span>),</span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"), la probabilidad de spam aumenta a"</span>, <span class="fu">round</span>(P_spam_top3, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Si aparecen las 3 palabras más frecuentes de spam ( call, å, now ), la probabilidad de spam aumenta a 0.999 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"- Si aparecen las 3 menos frecuentes de spam ("</span>, <span class="fu">paste</span>(bottom3_spam, <span class="at">collapse =</span> <span class="st">", "</span>),</span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"), la probabilidad baja a"</span>, <span class="fu">round</span>(P_spam_bottom3, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>- Si aparecen las 3 menos frecuentes de spam ( jurong, point, bugis ), la probabilidad baja a 0.156 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (P_spam_top3 <span class="sc">&gt;</span> P_spam_bottom3) {</span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> Conclusión: las palabras más frecuentes en spam aumentan significativamente la probabilidad posterior de que un mensaje sea spam.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb145-3"><a href="#cb145-3" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb145-4"><a href="#cb145-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> Conclusión: las palabras más frecuentes no son buenos predictores del spam en este corpus.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb145-5"><a href="#cb145-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Conclusión: las palabras más frecuentes en spam aumentan significativamente la probabilidad posterior de que un mensaje sea spam.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> Top 10 palabras que MÁS aumentan la probabilidad de spam:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Top 10 palabras que MÁS aumentan la probabilidad de spam:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(resumen[<span class="fu">order</span>(<span class="sc">-</span>resumen<span class="sc">$</span>P_spam_dado_palabra), ], <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              palabra P_spam_dado_palabra  efecto
claim           claim              0.9909 Aumenta
prize           prize              0.9883 Aumenta
won               won              0.9866 Aumenta
150p             150p              0.9850 Aumenta
guaranteed guaranteed              0.9807 Aumenta
å                   å              0.9795 Aumenta
cs                 cs              0.9782 Aumenta
tone             tone              0.9767 Aumenta
awarded       awarded              0.9749 Aumenta
150ppm         150ppm              0.9722 Aumenta</code></pre>
</div>
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st"> Top 10 palabras que MÁS reducen la probabilidad de spam:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Top 10 palabras que MÁS reducen la probabilidad de spam:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb153"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">head</span>(resumen[<span class="fu">order</span>(resumen<span class="sc">$</span>P_spam_dado_palabra), ], <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        palabra P_spam_dado_palabra efecto
lt           lt              0.0041 Reduce
gt           gt              0.0041 Reduce
lor         lor              0.0068 Reduce
da           da              0.0074 Reduce
later     later              0.0074 Reduce
ì_           ì_              0.0101 Reduce
say         say              0.0111 Reduce
ask         ask              0.0117 Reduce
said       said              0.0122 Reduce
morning morning              0.0130 Reduce</code></pre>
</div>
</div>
<p>El análisis bayesiano aplicado a la base de datos de mensajes tiene como objetivo entender cómo ciertas palabras modifican la probabilidad de que un mensaje sea clasificado como spam. Inicialmente, la proporción de mensajes spam dentro del conjunto total es del <strong>13,4 %</strong>, es decir, P(Spam)=0.134. Esto representa la probabilidad <em>a priori</em>, antes de observar ninguna palabra del texto.</p>
<p>Al examinar la distribución de términos, las <strong>palabras más frecuentes en los mensajes spam</strong> son <strong>“call”</strong>, <strong>“å”</strong> y <strong>“now”</strong>, mientras que las <strong>menos frecuentes</strong> son <strong>“jurong”</strong>, <strong>“point”</strong> y <strong>“bugis”</strong>. En contraste, los mensajes no spam suelen incluir con más frecuencia <strong>“u”</strong>, <strong>“can”</strong> y <strong>“now”</strong>, y con menor frecuencia <strong>“entry”</strong>, <strong>“wkly”</strong> y <strong>“fa”</strong>. Este patrón indica que algunos términos son marcadores muy característicos de contenido promocional o automatizado, mientras que otros son específicos de conversaciones personales.</p>
<p>Cuando se calculan las probabilidades condicionales, los resultados muestran que la presencia de palabras muy comunes en spam <strong>incrementa drásticamente la probabilidad posterior</strong> de que un mensaje sea spam. Concretamente:</p>
<ul>
<li><p>P(Spam)=0.134 (probabilidad inicial o <em>a priori</em>)</p></li>
<li><p>P(Spam∣call,&nbsp;a˚,&nbsp;now)=0.999</p></li>
<li><p>P(Spam∣jurong,&nbsp;point,&nbsp;bugis)=0.156</p></li>
</ul>
<p>Esto significa que, antes de observar el texto, la probabilidad de que un mensaje sea spam era del 13,4 %, pero al detectar simultáneamente las palabras <strong>“call”</strong>, <strong>“å”</strong> y <strong>“now”</strong>, la probabilidad posterior se eleva al <strong>99,9 %</strong>, prácticamente certeza. Por el contrario, si aparecen las palabras <strong>“jurong”</strong>, <strong>“point”</strong> y <strong>“bugis”</strong>, la probabilidad disminuye levemente hasta el <strong>15,6 %</strong>, sugiriendo que son términos asociados a mensajes no promocionales.</p>
<p>Este comportamiento refleja con precisión el <strong>principio del teorema de Bayes</strong>, donde las evidencias (las palabras) actualizan la creencia previa sobre la clase del mensaje. Las palabras más características de spam poseen una probabilidad condicional P(Palabra∣Spam) mucho mayor que P(Palabra∣No&nbsp;Spam), lo que hace que la razón bayesiana se incline fuertemente hacia la categoría spam.</p>
<p>El ranking de términos más influyentes refuerza esta conclusión. Las palabras <strong>“claim”</strong>, <strong>“prize”</strong>, <strong>“won”</strong>, <strong>“guaranteed”</strong> y <strong>“awarded”</strong> presentan las probabilidades condicionales más altas de spam (por encima de 0.97), lo que las convierte en <strong>indicadores casi inequívocos de contenido publicitario o fraudulento</strong>. En cambio, palabras como <strong>“lt”</strong>, <strong>“gt”</strong>, <strong>“lor”</strong>, <strong>“later”</strong>, <strong>“say”</strong> o <strong>“morning”</strong> tienen probabilidades inferiores al 0.02, lo que indica que <strong>reducen la probabilidad de spam</strong> y son más propias de lenguaje conversacional o cotidiano.</p>
<p>En conjunto, el modelo muestra que las <strong>palabras más frecuentes y características del spam aumentan de manera muy significativa la probabilidad posterior</strong> de que un mensaje sea spam. Esto valida la hipótesis bayesiana de que ciertos patrones léxicos actúan como señales predictivas claras. En términos prácticos, un mensaje que contenga varias de estas palabras (“call”, “claim”, “win”, “prize”, “guaranteed”) puede clasificarse como spam con altísima confianza.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>