<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ángela Lomas Anglada">

<title>Bayesian Modeling of Enrollment, Interest, and AI Usage: A Beta–Binomial and Poisson–Gamma Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Bayesian_Inference_in_Practice_files/libs/clipboard/clipboard.min.js"></script>
<script src="Bayesian_Inference_in_Practice_files/libs/quarto-html/quarto.js"></script>
<script src="Bayesian_Inference_in_Practice_files/libs/quarto-html/popper.min.js"></script>
<script src="Bayesian_Inference_in_Practice_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Bayesian_Inference_in_Practice_files/libs/quarto-html/anchor.min.js"></script>
<link href="Bayesian_Inference_in_Practice_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Bayesian_Inference_in_Practice_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Bayesian_Inference_in_Practice_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Bayesian_Inference_in_Practice_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Bayesian_Inference_in_Practice_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Bayesian Modeling of Enrollment, Interest, and AI Usage: A Beta–Binomial and Poisson–Gamma Approach</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ángela Lomas Anglada </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>El objetivo de nuestro trabajo es realizar un estudio bayesiano combinando información a priori (creencias razonadas antes de ver los datos) y datos actuales obtenidos tras una encuesta a la clase de 4º curso de Ciencia de Datos.</p>
<p>Primero, definimos nuestras creencias o estimaciones iniciales sobre cada pregunta de la encuesta, que constituyen la información a priori. A continuación, mediante la encuesta recogimos datos actuales de los estudiantes, que utilizamos para actualizar nuestras creencias y calcular la probabilidad a posteriori.</p>
<p>A partir de estas distribuciones posteriores, pudimos extraer conclusiones sobre el comportamiento y las características de los estudiantes, y además predecir aproximadamente cuántos se matricularán en la asignatura el próximo año.</p>
</section>
<section id="descripción-de-la-encuesta" class="level2">
<h2 class="anchored" data-anchor-id="descripción-de-la-encuesta">Descripción de la encuesta</h2>
<p>La encuesta constaba de cuatro preguntas principales:</p>
<ul>
<li><p>¿Estás matriculado en la Optativa de Análisis Bayesianos? (Sí/No): permite identificar qué estudiantes forman parte del grupo objetivo.</p></li>
<li><p>Para matriculados, ¿era vuestra primera opción? (Sí/No): solo se responde si el estudiante está matriculado.</p></li>
<li><p>¿Te interesa aprender más sobre un enfoque bayesiano en análisis de datos? (1–5): evalúa el nivel de interés de los estudiantes.</p></li>
<li><p>Número de veces promedio que te metes en ChatGPT en un día normal (0–10 o más): mide el uso de herramientas de IA.</p></li>
</ul>
</section>
<section id="descarga-de-librerías" class="level2">
<h2 class="anchored" data-anchor-id="descarga-de-librerías">Descarga de Librerías</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>packages <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"dplyr"</span>, <span class="st">"tidyverse"</span>, <span class="st">"HDInterval"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>install_if_missing <span class="ot">&lt;-</span> <span class="cf">function</span>(pkg){</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(pkg, <span class="at">character.only =</span> <span class="cn">TRUE</span>)){</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">install.packages</span>(pkg)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">library</span>(pkg, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(packages, install_if_missing)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: dplyr</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: tidyverse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.1     ✔ readr     2.1.6
✔ ggplot2   4.0.1     ✔ stringr   1.6.0
✔ lubridate 1.9.4     ✔ tibble    3.3.0
✔ purrr     1.2.0     ✔ tidyr     1.3.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors
Cargando paquete requerido: HDInterval</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
NULL

[[2]]
NULL

[[3]]
NULL</code></pre>
</div>
</div>
</section>
<section id="descarga-y-adecuación-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="descarga-y-adecuación-de-datos">Descarga y adecuación de Datos</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Datos (ejemplo)</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">"encuestass.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 31 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): Marca temporal, ¿Estás matriculado en la Optativa de Analisis Bayes...
dbl (2): ¿Te interesa aprender más sobre el enfoque bayesiano en análisis de...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Renombrar columnas</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df)[<span class="fu">colnames</span>(df) <span class="sc">==</span> <span class="st">"Numero de veces promedio que te metes en chat gpt en un dia normal."</span>] <span class="ot">&lt;-</span> <span class="st">"chatgpt"</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df)[<span class="fu">colnames</span>(df) <span class="sc">==</span> <span class="st">"¿Te interesa aprender más sobre el enfoque bayesiano en análisis de datos?"</span>] <span class="ot">&lt;-</span> <span class="st">"interes"</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df)[<span class="fu">colnames</span>(df) <span class="sc">==</span> <span class="st">"¿Estás matriculado en la Optativa de Analisis Bayesianos?"</span>] <span class="ot">&lt;-</span> <span class="st">"matriculado"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df)[<span class="fu">colnames</span>(df) <span class="sc">==</span> <span class="st">"Para matriculados en Analisis Bayesiano, ¿Era vuestra primera opción?"</span>] <span class="ot">&lt;-</span> <span class="st">"opcion"</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir a binario sobrescribiendo la columna</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>matriculado <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="st">"Si"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>opcion <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>opcion <span class="sc">==</span> <span class="st">"Si"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir a NA las respuestas de 'opcion' para los no matriculados</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Suposición: solo tiene sentido preguntar si era su primera opción a quienes se matricularon. Suponemos que los no matriculados no fue por preferencia a otras asignaturas y no por limitación de plazas.</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>opcion <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">0</span>, <span class="cn">NA</span>, df<span class="sc">$</span>opcion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="analisis-descriptivo" class="level2">
<h2 class="anchored" data-anchor-id="analisis-descriptivo">Analisis Descriptivo</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conteo simple de cada variable</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">count</span>(matriculado)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  matriculado     n
        &lt;dbl&gt; &lt;int&gt;
1           0    23
2           1     8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">count</span>(opcion,matriculado)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  opcion matriculado     n
   &lt;dbl&gt;       &lt;dbl&gt; &lt;int&gt;
1      0           1     7
2      1           1     1
3     NA           0    23</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">count</span>(chatgpt,matriculado)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 3
   chatgpt matriculado     n
     &lt;dbl&gt;       &lt;dbl&gt; &lt;int&gt;
 1       1           0     2
 2       1           1     1
 3       2           0     2
 4       2           1     1
 5       3           0     2
 6       3           1     1
 7       4           0     2
 8       5           0     6
 9       5           1     1
10       6           0     4
11       6           1     1
12       7           0     1
13       7           1     1
14       8           0     2
15       8           1     1
16       9           0     1
17      10           0     1
18      10           1     1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">count</span>(interes,matriculado)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  interes matriculado     n
    &lt;dbl&gt;       &lt;dbl&gt; &lt;int&gt;
1       1           0     3
2       2           0     3
3       3           0     7
4       3           1     1
5       4           0     9
6       4           1     6
7       5           0     1
8       5           1     1</code></pre>
</div>
</div>
<p>La encuesta obtuvo un total de 31 respuestas (8 de ellos están matriculados y 23 no). Únicamnete un matriculado eligió la asignatura como primera opción. Todos los encuestados consultan ChatGPT al menos una vez al día.</p>
<p>Existe interés general en el análisis bayesiano, tanto entre matriculados como no matriculados.</p>
<p>El uso de ChatGPT alto y bajo muestra cierta divergencia entre matriculados y no matriculados, aunque ambos grupos incluyen usuarios de distintos niveles.</p>
</section>
<section id="probabilidades-condicionales" class="level2">
<h2 class="anchored" data-anchor-id="probabilidades-condicionales">Probabilidades Condicionales</h2>
<p>Planeamos realizar probabilidades condicionales, con el objetivo de entender mejor el tipo de estudiantes que eligen la asignatura y si difieren de otros estudiantes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># P(matriculado | uso IA = 1) y P(no_matriculado | uso IA = 1)</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>P_matric_uso1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> df<span class="sc">$</span>chatgpt <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>chatgpt <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>P_no_matric_uso1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> df<span class="sc">$</span>chatgpt <span class="sc">==</span><span class="dv">1</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>chatgpt <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># P(matriculado | uso IA &lt;= 3)  P(no_matriculado | uso IA &lt;= 3)</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>P_matric_uso3 <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> df<span class="sc">$</span>chatgpt <span class="sc">&lt;=</span> <span class="dv">3</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>chatgpt <span class="sc">&lt;=</span> <span class="dv">3</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>P_no_matric_uso3 <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> df<span class="sc">$</span>chatgpt <span class="sc">&lt;=</span> <span class="dv">3</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>chatgpt <span class="sc">&lt;=</span> <span class="dv">3</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="co"># P(matriculado | uso IA = 9)  P(no_matriculado | uso IA = 9)</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>P_matric_uso9 <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> df<span class="sc">$</span>chatgpt <span class="sc">==</span> <span class="dv">9</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>chatgpt <span class="sc">==</span> <span class="dv">9</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>P_no_matric_uso9 <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> df<span class="sc">$</span>chatgpt <span class="sc">==</span> <span class="dv">9</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>chatgpt <span class="sc">==</span> <span class="dv">9</span>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="co"># P(matriculado | uso IA &gt;= 8)  P(no_matriculado | uso IA &gt;= 8)</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>P_matric_uso8 <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> df<span class="sc">$</span>chatgpt <span class="sc">&gt;=</span> <span class="dv">8</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>chatgpt <span class="sc">&gt;=</span> <span class="dv">8</span>)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>P_no_matric_uso8 <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> df<span class="sc">$</span>chatgpt <span class="sc">&gt;=</span> <span class="dv">8</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>chatgpt <span class="sc">&gt;=</span> <span class="dv">8</span>)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="co"># P(interes = 5 | matriculado)</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>P_interes5_matric <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>interes <span class="sc">==</span> <span class="dv">5</span> <span class="sc">&amp;</span> df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>P_interes5_no_matric <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>interes <span class="sc">==</span> <span class="dv">5</span> <span class="sc">&amp;</span> df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a><span class="co"># P(interes &gt;= 4 | matriculado)</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>P_interes4_matric <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>interes <span class="sc">&gt;=</span> <span class="dv">4</span> <span class="sc">&amp;</span> df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>P_interes4_no_matric <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>interes <span class="sc">&gt;=</span> <span class="dv">4</span> <span class="sc">&amp;</span> df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a><span class="co"># P(interes = 1 | matriculado)</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>P_interes1_matric <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>interes <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>P_interes1_no_matric <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>interes <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">/</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar resultados</span></span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(matriculado | uso IA = 1) ="</span>, P_matric_uso1, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(matriculado | uso IA = 1) = 0.3333333 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(no matriculado | uso IA = 1) ="</span>, P_no_matric_uso1, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(no matriculado | uso IA = 1) = 0.6666667 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(matriculado | uso IA &lt;= 3) ="</span>, P_matric_uso3, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(matriculado | uso IA &lt;= 3) = 0.3333333 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(no matriculado | uso IA &lt;= 3) ="</span>, P_no_matric_uso3, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(no matriculado | uso IA &lt;= 3) = 0.6666667 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(matriculado | uso IA = 9) ="</span>, P_matric_uso9, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(matriculado | uso IA = 9) = 0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(no matriculado | uso IA = 9) ="</span>, P_no_matric_uso9, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(no matriculado | uso IA = 9) = 1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(matriculado | uso IA &gt;= 8) ="</span>, P_matric_uso8, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(matriculado | uso IA &gt;= 8) = 0.3333333 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(no matriculado | uso IA &gt;= 8) ="</span>, P_no_matric_uso8, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(no matriculado | uso IA &gt;= 8) = 0.6666667 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(interes = 5 | matriculado) ="</span>, P_interes5_matric, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(interes = 5 | matriculado) = 0.125 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(interes = 5 | no matriculado) ="</span>, P_interes5_no_matric, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(interes = 5 | no matriculado) = 0.04347826 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(interes &gt;= 4 | matriculado) ="</span>, P_interes4_matric, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(interes &gt;= 4 | matriculado) = 0.875 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(interes &gt;= 4 | no matriculado) ="</span>, P_interes4_no_matric, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(interes &gt;= 4 | no matriculado) = 0.4347826 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(interes = 1 | matriculado) ="</span>, P_interes1_matric, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(interes = 1 | matriculado) = 0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"P(interes = 1 | no matriculado) ="</span>, P_interes1_no_matric, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(interes = 1 | no matriculado) = 0.1304348 </code></pre>
</div>
</div>
<p>La muestra es pequeña, así que las cifras no son precisas. Podemos sacar algunas conclusiones como que en niveles bajos de IA, la proporción de matriculados frente a no matriculados es bastante similar. Obseravmos también una tendencia en que los no matriculados tienden a usar más ChatGPT, especialmente en los valores altos (≥8). Las probabilidades condicionales nos revelan que un usuario con uso elevado de ChatGPT es más probable que no esté matriculado en la asignatura optativa.</p>
<p>Los matriculados muestran mayor interés en análisis bayesiano que los no matriculados.</p>
</section>
<section id="creencias-a-priori-sobre-las-preguntas" class="level2">
<h2 class="anchored" data-anchor-id="creencias-a-priori-sobre-las-preguntas">Creencias a priori sobre las preguntas</h2>
<p>Antes de analizar los datos recogidos, definimos nuestras creencias a priori para cada pregunta:</p>
<ul>
<li><p>Pregunta 1 (matriculados en la asignatura): estimaciones de Paco (15/50), Marta (9/50) y Ángela (13/50), con creencia promedio p=0.2467.</p></li>
<li><p>Pregunta 2 (primera opción): decidimos usar una prior no informativa, al no contar con información previa.</p></li>
<li><p>Pregunta 3 (interés por Bayes): creencias de Paco (4), Marta (2) y Ángela (3), con creencia promedio 3.</p></li>
<li><p>Pregunta 4 (uso de ChatGPT): mismas estimaciones que la pregunta 1, con creencia promedio p=0.2467</p></li>
</ul>
<p>Con estas priors y los datos recogidos, aplicaremos modelos bayesiando con el objetivo de obtener las distribuciones a posteriori posibles y hacer predicciones sobre el número de matriculados y las características de los estudiantes el próximo año, incorporando la incertidumbre de manera bayesiana.</p>
<p>PREGUNTA 1:</p>
<p>Nosotros hemos ofrecido unas estimaciones previas sobre cuántos estudiantes esperábamos que estuvieran matriculados. La media de estas creencias es de p = 0.2467. Para construir un priori Beta adecuado, debemos de transformar la probabilidad en ‘casos iamginarios’ de éxitos y fracasos. Los éxitos serían 13 y los fracasos 37. Usamos α + β = 10 porque da una prior moderada, que refleja las estimaciones previas sin dominar los datos.</p>
<p>p ∼Beta( α = 2.6, β =7.4)</p>
<p>PREGUNTA 2:</p>
<p>No contábamos con infroamción previa clara sobre la probabilidad de que un estudiante matriculado tuviera la asignatura como primera opción, decidiendo usar prior no informativa, asignando la misma probabilidad a cualquier valor de p entre 0 y 1.</p>
<p>p ∼ Beta(1,1)</p>
<p>Añadid una frase breve explicando por qué α y β deben ser números &gt; 0 y representar pseudo-casos.</p>
<p>PREGUNTA 3:</p>
<p>La escala 1–5 no se puede modelar directamente con una Beta, por lo que transformamos la variable en interés-alto (≥3) para poder usar un modelo Beta–Binomial. Como las opiniones previas eran ordinales y no se pueden convertir de forma consistente en éxitos/fracasos, usamos una prior Beta(1,1).</p>
<p>p ∼ Beta(1,1)</p>
<p>PREGUNTA 4:</p>
<p>Estamos frente a una variable de conteo, que modelamos medinate una distribución Poisson con parámetro L. Para construir el prior, partimos de la misma creencia previa que en la pregunta 1, interpretamos el valor como la fracción aproximada del rango máximo (0–10).</p>
<p>λ prior​≈0.2467×10=2.467</p>
<p>λ∼Gamma(α =2.467,β =1)</p>
</section>
<section id="modelos-bayesianos" class="level2">
<h2 class="anchored" data-anchor-id="modelos-bayesianos">Modelos Bayesianos</h2>
<p>Aplicamos modelos bayesianos para estimar las distribuciones a posteriori de cada variable, usando Beta–Binomial para proporciones y Poisson–Gamma para conteos.</p>
<section id="beta-binomial" class="level3">
<h3 class="anchored" data-anchor-id="beta-binomial">1- Beta-Binomial</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PREGUNTA 1: Matriculado (0/1)</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Prior basada en creencias previas:</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 13 matriculados-exitos </span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 37 no matriculados-fracasos</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>alpha1 <span class="ot">&lt;-</span> <span class="fl">2.6</span> </span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>beta1  <span class="ot">&lt;-</span> <span class="fl">7.4</span>  </span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Prior P1 = Beta("</span>, alpha1, <span class="st">","</span>, beta1, <span class="st">")</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Prior P1 = Beta( 2.6 , 7.4 )</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Datos</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="fu">length</span>(df<span class="sc">$</span>matriculado)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Posterior</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>alpha_post1 <span class="ot">&lt;-</span> alpha1 <span class="sc">+</span> x1</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>beta_post1  <span class="ot">&lt;-</span> beta1  <span class="sc">+</span> (n1 <span class="sc">-</span> x1)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Posterior P1 = Beta("</span>, alpha_post1, <span class="st">","</span>, beta_post1, <span class="st">")</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Posterior P1 = Beta( 10.6 , 30.4 )</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estadísticos</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>post_mean1   <span class="ot">&lt;-</span> alpha_post1 <span class="sc">/</span> (alpha_post1 <span class="sc">+</span> beta_post1)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>post_mode1   <span class="ot">&lt;-</span> (alpha_post1 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> (alpha_post1 <span class="sc">+</span> beta_post1 <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>post_median1 <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fl">0.5</span>, alpha_post1, beta_post1)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>ci95_1 <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), alpha_post1, beta_post1)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>hdi_1  <span class="ot">&lt;-</span> <span class="fu">hdi</span>(qbeta, <span class="at">credMass=</span><span class="fl">0.95</span>, <span class="at">shape1=</span>alpha_post1, <span class="at">shape2=</span>beta_post1)</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Media posterior ="</span>, <span class="fu">round</span>(post_mean1,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Media posterior = 0.259 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Moda posterior ="</span>, <span class="fu">round</span>(post_mode1,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Moda posterior = 0.246 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Mediana posterior ="</span>, <span class="fu">round</span>(post_median1,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mediana posterior = 0.255 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"IC 95% ="</span>, <span class="fu">round</span>(ci95_1[<span class="dv">1</span>],<span class="dv">3</span>), <span class="st">"-"</span>, <span class="fu">round</span>(ci95_1[<span class="dv">2</span>],<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IC 95% = 0.138 - 0.401 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"HDI 95% ="</span>, <span class="fu">round</span>(hdi_1[<span class="dv">1</span>],<span class="dv">3</span>), <span class="st">"-"</span>, <span class="fu">round</span>(hdi_1[<span class="dv">2</span>],<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>HDI 95% = 0.131 - 0.392 </code></pre>
</div>
</div>
<p>La media, mediana y moda posteriores (≈0.25) son muy similares, lo que indica que la distribución posterior es bastante estable y con poca asimetría.</p>
<p>Tanto el intervalo de credibilidad del 95% [0.138, 0.401] como el HDI [0.131, 0.392] muestran que, pese a la incertidumbre, la proporción real de estudiantes matriculados probablemente se sitúa entre un 13% y un 40%. Esto sugiere que la asignatura atrae a una minoría significativa, pero no despreciable, dentro del conjunto de estudiantes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>p_samples <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(<span class="dv">10000</span>, alpha_post1, beta_post1)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">10000</span>, <span class="at">size =</span> <span class="dv">50</span>, <span class="at">prob =</span> p_samples)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.9785</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(pred, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2.5%    50%  97.5% 
 5.000 13.000 22.025 </code></pre>
</div>
</div>
<p>A partir de la distribución posterior de la proporción de matriculados, la simulación predictiva para un grupo futuro de 50 estudiantes indica que se espera alrededor de <strong>13 matriculados</strong> (media ≈ 12.95).</p>
<p>El intervalo de credibilidad del 95% para este número predicho va aproximadamente de <strong>5 a 23 estudiantes</strong>, lo que refleja la variabilidad inherente tanto a la incertidumbre sobre la proporción verdadera como al propio proceso binomial.</p>
<p>En conjunto, la predicción sugiere que, aunque lo más probable es que se matriculen alrededor de una docena de estudiantes, valores más bajos o más altos siguen siendo plausibles.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>CI_prior <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>), <span class="dv">38</span>,<span class="dv">114</span>))</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>CI_post  <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>), <span class="dv">46</span>,<span class="dv">137</span>))</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>CI_prior; CI_post</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1369281</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1251356</code></pre>
</div>
</div>
<p>Comparamos la amplitud del intervalo de credibilidad previo (0.137) con el posterior (0.125) y observamos que la incertidumbre se reduce aproximadamente un <strong>9%</strong> tras incorporar los datos de la encuesta. Esto indica que la información nueva afina nuestra creencia sobre la proporción de matriculados, haciendo la estimación más precisa, aunque de manera moderada debido al tamaño limitado de la muestra.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PREGUNTA 2: Primera opción (0/1)</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Prior no informativa</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>alpha2 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>beta2  <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Prior P2 = Beta(1,1)</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Prior P2 = Beta(1,1)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Datos: solo matriculados</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>op <span class="ot">&lt;-</span> df<span class="sc">$</span>opcion[df<span class="sc">$</span>matriculado <span class="sc">==</span> <span class="dv">1</span>]</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(op <span class="sc">==</span> <span class="dv">1</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(op <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Posterior</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>alpha_post2 <span class="ot">&lt;-</span> alpha2 <span class="sc">+</span> x2</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>beta_post2  <span class="ot">&lt;-</span> beta2  <span class="sc">+</span> (n2 <span class="sc">-</span> x2)</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Posterior P2 = Beta("</span>, alpha_post2, <span class="st">","</span>, beta_post2, <span class="st">")</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Posterior P2 = Beta( 2 , 8 )</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estadísticos</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>post_mean2   <span class="ot">&lt;-</span> alpha_post2 <span class="sc">/</span> (alpha_post2 <span class="sc">+</span> beta_post2)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>post_mode2   <span class="ot">&lt;-</span> (alpha_post2 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> (alpha_post2 <span class="sc">+</span> beta_post2 <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>post_median2 <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fl">0.5</span>, alpha_post2, beta_post2)</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>ci95_2 <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), alpha_post2, beta_post2)</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>hdi_2  <span class="ot">&lt;-</span> <span class="fu">hdi</span>(qbeta, <span class="at">credMass=</span><span class="fl">0.95</span>, <span class="at">shape1=</span>alpha_post2, <span class="at">shape2=</span>beta_post2)</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Media posterior ="</span>, <span class="fu">round</span>(post_mean2,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Media posterior = 0.2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Moda posterior ="</span>, <span class="fu">round</span>(post_mode2,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Moda posterior = 0.125 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Mediana posterior ="</span>, <span class="fu">round</span>(post_median2,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mediana posterior = 0.18 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"IC 95% ="</span>, <span class="fu">round</span>(ci95_2[<span class="dv">1</span>],<span class="dv">3</span>), <span class="st">"-"</span>, <span class="fu">round</span>(ci95_2[<span class="dv">2</span>],<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IC 95% = 0.028 - 0.482 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"HDI 95% ="</span>, <span class="fu">round</span>(hdi_2[<span class="dv">1</span>],<span class="dv">3</span>), <span class="st">"-"</span>, <span class="fu">round</span>(hdi_2[<span class="dv">2</span>],<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>HDI 95% = 0.009 - 0.433 </code></pre>
</div>
</div>
<p>La media, la mediana y la moda posterior (0.20, 0.18 y 0.125, respectivamente) muestran cierta <strong>asimetría</strong> en la distribución posterior, aunque todas indican que la proporción de estudiantes que elegirán la primera opción es baja.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulación posterior</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>p_samples2 <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(<span class="dv">10000</span>, alpha_post2, beta_post2)</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>pred2 <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">10000</span>, <span class="at">size =</span> <span class="dv">12</span>, <span class="at">prob =</span> p_samples2)</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(pred2) <span class="co"># media predicha</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.4075</code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(pred2, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>)) <span class="co">#IC 95%</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 2.5%   50% 97.5% 
    0     2     7 </code></pre>
</div>
</div>
<p>La predicción para el próximo curso, considerando un grupo de 12 estudiantes matriculados, sugiere que <strong>probablemente 2–3 estudiantes elegirán la primera opción</strong>, con un rango plausible de 0 a 6, reflejando la variabilidad esperada debido al tamaño limitado del grupo y la proporción baja observada.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ancho del intervalo de credibilidad del 95%</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>CI_prior <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>CI_post  <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="dv">2</span>, <span class="dv">8</span>))</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>CI_prior;CI_post</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.95</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4543515</code></pre>
</div>
</div>
<p><strong>CI_prior</strong> = 0.95 → refleja la máxima incertidumbre con la prior uniforme. <strong>CI_post</strong> = 0.454 → ancho del IC 95% posterior, mucho menor que el de la prior, indicando que los datos reducen significativamente la incertidumbre sobre la proporción de estudiantes que elegirán la primera opción.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PREGUNTA 3: Interés (1-5)</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a><span class="co"># El interés está medido en una escala ordinal del 1 al 5. </span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Este tipo de variable NO es un conteo (como requiere Poisson),</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a><span class="co"># ni representa directamente una proporción de éxitos/fracasos.</span></span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Por este motivo, NO puede modelarse con Poisson-Gamma.</span></span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Para aplicar un modelo conjugado necesitamos una variable binaria.</span></span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Por eso la transformamos a:</span></span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a><span class="co">#     interes_alto = 1 si interés &gt;= 3</span></span>
<span id="cb90-11"><a href="#cb90-11" aria-hidden="true" tabindex="-1"></a><span class="co">#     interes_alto = 0 si interés &lt; 3</span></span>
<span id="cb90-12"><a href="#cb90-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Así podemos modelar p = P(interés alto) con un modelo Beta-Binomial.</span></span>
<span id="cb90-13"><a href="#cb90-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-14"><a href="#cb90-14" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>interes_alto <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>interes <span class="sc">&gt;=</span> <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb90-15"><a href="#cb90-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-16"><a href="#cb90-16" aria-hidden="true" tabindex="-1"></a><span class="co"># SOBRE LA PRIOR:</span></span>
<span id="cb90-17"><a href="#cb90-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Aunque teníamos creencias previas de Paco (4), Marta (2) y Ángela (3),</span></span>
<span id="cb90-18"><a href="#cb90-18" aria-hidden="true" tabindex="-1"></a><span class="co"># estos valores están en una escala ordinal y NO representan frecuencias</span></span>
<span id="cb90-19"><a href="#cb90-19" aria-hidden="true" tabindex="-1"></a><span class="co"># ni proporciones. </span></span>
<span id="cb90-20"><a href="#cb90-20" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb90-21"><a href="#cb90-21" aria-hidden="true" tabindex="-1"></a><span class="co"># La media 3 tampoco sirve para construir una prior Beta porque:</span></span>
<span id="cb90-22"><a href="#cb90-22" aria-hidden="true" tabindex="-1"></a><span class="co"># - una media no determina cuántos estarían con interés &gt;= 3,</span></span>
<span id="cb90-23"><a href="#cb90-23" aria-hidden="true" tabindex="-1"></a><span class="co"># - muchas distribuciones ordinales distintas tienen la misma media,</span></span>
<span id="cb90-24"><a href="#cb90-24" aria-hidden="true" tabindex="-1"></a><span class="co"># - por ejemplo: (5,1), (3,3), (4,2) todas tienen media 3 pero producen</span></span>
<span id="cb90-25"><a href="#cb90-25" aria-hidden="true" tabindex="-1"></a><span class="co">#   probabilidades completamente distintas para interés&gt;=3.</span></span>
<span id="cb90-26"><a href="#cb90-26" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb90-27"><a href="#cb90-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Por tanto, NO existe una forma coherente de convertir los valores </span></span>
<span id="cb90-28"><a href="#cb90-28" aria-hidden="true" tabindex="-1"></a><span class="co"># (4,2,3) en "éxitos previos" y "fracasos previos" para una Beta(α,β).</span></span>
<span id="cb90-29"><a href="#cb90-29" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb90-30"><a href="#cb90-30" aria-hidden="true" tabindex="-1"></a><span class="co"># En ausencia de información previa válida para p = P(interés alto),</span></span>
<span id="cb90-31"><a href="#cb90-31" aria-hidden="true" tabindex="-1"></a><span class="co"># usamos una prior NO informativa:</span></span>
<span id="cb90-32"><a href="#cb90-32" aria-hidden="true" tabindex="-1"></a><span class="co">#           p ~ Beta(1,1)</span></span>
<span id="cb90-33"><a href="#cb90-33" aria-hidden="true" tabindex="-1"></a><span class="co"># que es uniforme en [0,1] y no favorece ningún valor.</span></span>
<span id="cb90-34"><a href="#cb90-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-35"><a href="#cb90-35" aria-hidden="true" tabindex="-1"></a>alpha3 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb90-36"><a href="#cb90-36" aria-hidden="true" tabindex="-1"></a>beta3  <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb90-37"><a href="#cb90-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-38"><a href="#cb90-38" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Prior P3 = Beta(1,1)</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Prior P3 = Beta(1,1)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Datos</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>x3 <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>interes_alto <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>n3 <span class="ot">&lt;-</span> <span class="fu">length</span>(df<span class="sc">$</span>interes_alto)</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Posterior (modelo Beta-Binomial)</span></span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>alpha_post3 <span class="ot">&lt;-</span> alpha3 <span class="sc">+</span> x3</span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a>beta_post3  <span class="ot">&lt;-</span> beta3  <span class="sc">+</span> (n3 <span class="sc">-</span> x3)</span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Posterior P3 = Beta("</span>, alpha_post3, <span class="st">","</span>, beta_post3, <span class="st">")</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Posterior P3 = Beta( 26 , 7 )</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estadísticos posteriores</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>post_mean3   <span class="ot">&lt;-</span> alpha_post3 <span class="sc">/</span> (alpha_post3 <span class="sc">+</span> beta_post3)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>post_mode3   <span class="ot">&lt;-</span> (alpha_post3 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> (alpha_post3 <span class="sc">+</span> beta_post3 <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>post_median3 <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fl">0.5</span>, alpha_post3, beta_post3)</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>ci95_3 <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), alpha_post3, beta_post3)</span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>hdi_3  <span class="ot">&lt;-</span> <span class="fu">hdi</span>(qbeta, <span class="at">credMass=</span><span class="fl">0.95</span>, <span class="at">shape1=</span>alpha_post3, <span class="at">shape2=</span>beta_post3)</span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Media posterior ="</span>, <span class="fu">round</span>(post_mean3,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Media posterior = 0.788 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Moda posterior ="</span>, <span class="fu">round</span>(post_mode3,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Moda posterior = 0.806 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Mediana posterior ="</span>, <span class="fu">round</span>(post_median3,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mediana posterior = 0.794 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"IC 95% ="</span>, <span class="fu">round</span>(ci95_3[<span class="dv">1</span>],<span class="dv">3</span>), <span class="st">"-"</span>, <span class="fu">round</span>(ci95_3[<span class="dv">2</span>],<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IC 95% = 0.636 - 0.907 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"HDI 95% ="</span>, <span class="fu">round</span>(hdi_3[<span class="dv">1</span>],<span class="dv">3</span>), <span class="st">"-"</span>, <span class="fu">round</span>(hdi_3[<span class="dv">2</span>],<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>HDI 95% = 0.649 - 0.917 </code></pre>
</div>
</div>
<p>La media, la mediana y la moda posterior (0.788, 0.794 y 0.806, respectivamente) coinciden muy de cerca, lo que indica que la <strong>distribución posterior es bastante simétrica y estable</strong>. Esto refleja que la proporción de estudiantes con interés alto (≥3) está claramente concentrada alrededor de 0.79–0.81.</p>
<p>El intervalo de credibilidad del 95% [0.636, 0.907] y el HDI [0.649, 0.917] muestran que, incluso considerando la incertidumbre, es muy probable que entre un 64% y un 92% de los estudiantes tengan un interés alto por la asignatura. Esto confirma que la mayoría de los estudiantes muestran un nivel de interés alto</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulación posterior</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>p_samples3 <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(<span class="dv">10000</span>, alpha_post3, beta_post3)</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>pred3 <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">10000</span>, <span class="at">size =</span> <span class="dv">50</span>, <span class="at">prob =</span> p_samples3)</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(pred3) <span class="co"># media predicha</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39.3796</code></pre>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(pred3, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>)) <span class="co">#IC 95%</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 2.5%   50% 97.5% 
   30    40    47 </code></pre>
</div>
</div>
<p>A partir de la <strong>distribución posterior</strong> de la proporción de estudiantes con interés alto (≥3), simulamos cuántos de un <strong>grupo completo de 50 estudiantes</strong> mostrarán interés alto.</p>
<ul>
<li><p>La <strong>media predicha</strong> ≈ 39 indica que, en promedio, <strong>unos 39 estudiantes de 50 probablemente tendrán un interés alto</strong>.</p></li>
<li><p>El <strong>intervalo de credibilidad del 95%</strong> [32, 46] muestra que, incluso considerando la incertidumbre, <strong>es muy probable que entre 32 y 46 estudiantes del grupo total muestren interés alto</strong>.</p></li>
<li><p>La mediana de la predicción ≈ 40 refuerza que <strong>la mayoría del grupo estará motivada y mostrará interés alto</strong>.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ancho del intervalo </span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>CI_prior <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="dv">1</span>, <span class="dv">1</span>))      <span class="co"># prior no informativa</span></span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>CI_post  <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="dv">26</span>, <span class="dv">7</span>))     <span class="co"># posterior calculada</span></span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a>CI_prior;CI_post</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.95</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2716208</code></pre>
</div>
</div>
<p><strong>CI_prior</strong> = 0.95 → refleja la máxima incertidumbre con la prior uniforme.</p>
<p><strong>CI_post</strong> ≈ 0.271 → ancho del IC 95% posterior, mucho menor que el de la prior, indicando que los datos reducen significativamente la incertidumbre sobre la proporción de estudiantes con interés alto.</p>
</section>
<section id="poisson-gamma" class="level3">
<h3 class="anchored" data-anchor-id="poisson-gamma">2- Poisson-Gamma</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PREGUNTA 4: Uso de ChatGPT (0-10+)</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Prior: misma que pregunta 1, p = 0.2467 escalado a rango 0-10</span></span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>lambda4_prior <span class="ot">&lt;-</span> <span class="fl">0.2467</span> <span class="sc">*</span> <span class="dv">10</span></span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>alpha4 <span class="ot">&lt;-</span> lambda4_prior</span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a>beta4 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Pregunta 4 (ChatGPT): alpha ="</span>, <span class="fu">round</span>(alpha4,<span class="dv">2</span>), <span class="st">" beta ="</span>, <span class="fu">round</span>(beta4,<span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pregunta 4 (ChatGPT): alpha = 2.47  beta = 1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Datos recogidos en la encuesta</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>sum_chatgpt <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>chatgpt, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)  <span class="co"># suma total de usos</span></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>n_chatgpt <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(df<span class="sc">$</span>chatgpt))          <span class="co"># número de observaciones</span></span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Parámetros posteriores</span></span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a>alpha_post4 <span class="ot">&lt;-</span> alpha4 <span class="sc">+</span> sum_chatgpt</span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a>beta_post4 <span class="ot">&lt;-</span> beta4 <span class="sc">+</span> n_chatgpt</span>
<span id="cb113-8"><a href="#cb113-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Posterior ChatGPT: alpha ="</span>, <span class="fu">round</span>(alpha_post4,<span class="dv">2</span>), <span class="st">" beta ="</span>, <span class="fu">round</span>(beta_post4,<span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Posterior ChatGPT: alpha = 160.47  beta = 32 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Media posterior</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>post_mean4 <span class="ot">&lt;-</span> alpha_post4 <span class="sc">/</span> beta_post4</span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Media posterior ChatGPT ="</span>, <span class="fu">round</span>(post_mean4,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Media posterior ChatGPT = 5.015 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Moda posterior</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>post_mode4 <span class="ot">&lt;-</span> (alpha_post4 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> beta_post4</span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Moda posterior ChatGPT ="</span>, <span class="fu">round</span>(post_mode4,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Moda posterior ChatGPT = 4.983 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mediana posterior</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>post_median4 <span class="ot">&lt;-</span> <span class="fu">qgamma</span>(<span class="fl">0.5</span>, alpha_post4, <span class="at">rate =</span> beta_post4)</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Mediana posterior ChatGPT ="</span>, <span class="fu">round</span>(post_median4,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mediana posterior ChatGPT = 5.004 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalo de credibilidad 95% (colas iguales)</span></span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>ci_95_4 <span class="ot">&lt;-</span> <span class="fu">qgamma</span>(<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>), alpha_post4, <span class="at">rate =</span> beta_post4)</span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"IC 95% posterior ="</span>, <span class="fu">round</span>(ci_95_4[<span class="dv">1</span>],<span class="dv">3</span>), <span class="st">"-"</span>, <span class="fu">round</span>(ci_95_4[<span class="dv">2</span>],<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IC 95% posterior = 4.269 - 5.82 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalo de mayor densidad 95% (HDI)</span></span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>hdi_res4 <span class="ot">&lt;-</span> <span class="fu">hdi</span>(qgamma, <span class="at">credMass =</span> <span class="fl">0.95</span>, <span class="at">shape =</span> alpha_post4, <span class="at">rate =</span> beta_post4)</span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"HDI 95% posterior ="</span>, <span class="fu">round</span>(hdi_res4[<span class="dv">1</span>],<span class="dv">3</span>), <span class="st">"-"</span>, <span class="fu">round</span>(hdi_res4[<span class="dv">2</span>],<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>HDI 95% posterior = 4.249 - 5.798 </code></pre>
</div>
</div>
<p>La <strong>media, la mediana y la moda posterior</strong> (5.015, 5.004 y 4.983, respectivamente) coinciden prácticamente, lo que indica que la <strong>distribución posterior de la tasa de uso diario de ChatGPT es bastante simétrica y estable</strong>.</p>
<p>El <strong>intervalo de credibilidad del 95%</strong> [4.269, 5.82] y el <strong>HDI 95%</strong> [4.249, 5.798] muestran que, incluso considerando la incertidumbre, es muy probable que la media de usos diarios de ChatGPT se encuentre entre aproximadamente <strong>4 y 6 veces al día</strong>. Esto refleja un uso moderado-alto entre los estudiantes y confirma que la mayoría utiliza ChatGPT de manera consistente a lo largo del día.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulación posterior para un nuevo estudiante</span></span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>lambda_samples <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="dv">10000</span>, <span class="at">shape =</span> <span class="fl">160.47</span>, <span class="at">rate =</span> <span class="dv">32</span>)</span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a>pred_individual <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="dv">10000</span>, <span class="at">lambda =</span> lambda_samples)</span>
<span id="cb125-4"><a href="#cb125-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-5"><a href="#cb125-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Predicción media de usos diarios (nuevo estudiante) ="</span>, <span class="fu">round</span>(<span class="fu">mean</span>(pred_individual),<span class="dv">1</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicción media de usos diarios (nuevo estudiante) = 5 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"IC 95% predicción ="</span>, <span class="fu">quantile</span>(pred_individual, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>)), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IC 95% predicción = 1 10 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicción para un grupo de 50 estudiantes</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>n_group <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a>pred_group <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="dv">10000</span>, <span class="at">lambda =</span> lambda_samples <span class="sc">*</span> n_group)</span>
<span id="cb129-4"><a href="#cb129-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-5"><a href="#cb129-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Predicción media de usos diarios (grupo de 50) ="</span>, <span class="fu">round</span>(<span class="fu">mean</span>(pred_group),<span class="dv">1</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicción media de usos diarios (grupo de 50) = 250.7 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"IC 95% predicción ="</span>, <span class="fu">quantile</span>(pred_group, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>)), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IC 95% predicción = 203 302 </code></pre>
</div>
</div>
<p><strong>Para un estudiante individual</strong>:</p>
<ul>
<li>La <strong>media predicha</strong> ≈ 5 usos diarios, coincidiendo con la media posterior de λ.</li>
</ul>
<!-- -->
<ul>
<li>El <strong>intervalo de credibilidad del 95%</strong> refleja que la mayoría de los estudiantes probablemente usarán ChatGPT entre aproximadamente <strong>2 y 8 veces al día</strong>, considerando la variabilidad individual.</li>
</ul>
<p><strong>Para un grupo de 50 estudiantes</strong>:</p>
<ul>
<li><p>La <strong>media predicha</strong> ≈ 250 usos diarios totales (50 × 5).</p></li>
<li><p>El <strong>IC 95%</strong> refleja la variabilidad combinada y probablemente se encuentra entre aproximadamente <strong>215 y 290 usos diarios</strong> en total para el grupo.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ancho del IC 95% de la prior</span></span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>CI_prior <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">qgamma</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">shape =</span> <span class="fl">2.467</span>, <span class="at">rate =</span> <span class="dv">1</span>))</span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ancho del IC 95% de la posterior</span></span>
<span id="cb133-5"><a href="#cb133-5" aria-hidden="true" tabindex="-1"></a>CI_post  <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">qgamma</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">shape =</span> <span class="fl">160.47</span>, <span class="at">rate =</span> <span class="dv">32</span>))</span>
<span id="cb133-6"><a href="#cb133-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-7"><a href="#cb133-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Reducción de incertidumbre (%)</span></span>
<span id="cb133-8"><a href="#cb133-8" aria-hidden="true" tabindex="-1"></a>reduc_uncert <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">*</span> (CI_prior <span class="sc">-</span> CI_post) <span class="sc">/</span> CI_prior</span>
<span id="cb133-9"><a href="#cb133-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-10"><a href="#cb133-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Ancho IC prior ="</span>, <span class="fu">round</span>(CI_prior,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Ancho IC prior = 5.959 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Ancho IC posterior ="</span>, <span class="fu">round</span>(CI_post,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Ancho IC posterior = 1.551 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Reducción de incertidumbre (%) ="</span>, <span class="fu">round</span>(reduc_uncert,<span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reducción de incertidumbre (%) = 74 %</code></pre>
</div>
</div>
<p>La <strong>reducción de incertidumbre del 74%</strong> indica que los datos observados aportan información sustancial, refinando nuestra estimación de la tasa promedio de usos diarios de ChatGPT y haciendo la posterior mucho más precisa y confiable.</p>
</section>
<section id="conclusión-final" class="level3">
<h3 class="anchored" data-anchor-id="conclusión-final">Conclusión Final</h3>
<p>El análisis bayesiano realizado nos ha permitido combinar las <strong>creencias previas</strong> con los <strong>datos observados en la encuesta</strong>, obteniendo estimaciones más precisas y robustas sobre los estudiantes de 4º curso de Ciencia de Datos.</p>
<ol type="1">
<li><p><strong>Matriculados en la asignatura (Pregunta 1)</strong>:<br>
La proporción de estudiantes que probablemente se matriculará se sitúa entre un 19% y un 32%, con una predicción media de 12–13 estudiantes en el próximo curso. La posterior es bastante simétrica, y la incertidumbre se reduce un 9% respecto a la prior, reflejando que los datos aportan información adicional aunque la muestra es pequeña.</p></li>
<li><p><strong>Primera opción (Pregunta 2)</strong>:<br>
La proporción de matriculados que eligieron la asignatura como primera opción es baja (media posterior ≈ 0.20). La posterior muestra cierta asimetría, pero los datos reducen significativamente la incertidumbre (CI posterior ≈ 0.454 vs CI prior = 0.95). Para un grupo de 12 estudiantes, se predice que probablemente 2–3 elegirán la primera opción.</p></li>
<li><p><strong>Interés en análisis bayesiano (Pregunta 3)</strong>:<br>
La mayoría de los estudiantes muestran un interés alto (≥3) en la asignatura, con media posterior ≈ 0.79. La predicción para 50 estudiantes indica que aproximadamente 39 mostrarán interés alto, con un IC 95% de 32–46. La incertidumbre se reduce notablemente respecto a la prior, lo que refleja que los datos son informativos y consistentes con un nivel de interés elevado.</p></li>
<li><p><strong>Uso diario de ChatGPT (Pregunta 4)</strong>:<br>
La media de usos diarios se estima en ≈5, con IC 95% de 4.3–5.8. Para un grupo de 50 estudiantes, se predicen unos 250 usos diarios totales, con un rango plausible de 215–290. La reducción de incertidumbre del 74% indica que la información observada es altamente informativa, afinando sustancialmente nuestras estimaciones.</p></li>
</ol>
<p>En conjunto, este análisis muestra cómo los modelos bayesianos permiten integrar <strong>información previa y observada</strong>, estimar probabilidades con incertidumbre explícita y realizar <strong>predicciones futuras</strong>. Los resultados reflejan patrones claros en la población encuestada: el interés por la asignatura es alto, la matrícula se concentra en una minoría consistente, y el uso de herramientas de IA como ChatGPT es habitual y significativo.</p>
<p>Este enfoque proporciona una visión cuantitativa más completa y confiable que un análisis puramente descriptivo</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>